In [8]:
import awkward as ak
import numpy as np
import pandas as pd
pd.set_option('display.max_columns', None)

In [2]:
fcp_dfd_sig24 = pd.read_parquet("/eos/uscms/store/group/lpcdihiggsboost/tsievert/HiggsDNA_parquet/DFDatasets/vManosv6/24_Manos_2026-04-20_12-49-04/Run3_2024/sim/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_preprocessed_test0.parquet")
fcp_preproc_sig24 = pd.read_parquet("/eos/uscms/store/group/lpcdihiggsboost/tsievert/HiggsDNA_parquet/preprocessed/v8/Run3_2024/sim/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_preprocessed.parquet")

In [5]:
fcp_dfd_sig24.head()

,eta,lead_eta,lead_phi,lead_mvaID,sublead_eta,sublead_phi,sublead_mvaID,nonResReg_vbfpair_lead_bjet_eta,nonResReg_vbfpair_lead_bjet_phi,nonResReg_vbfpair_lead_bjet_bTagWPL,nonResReg_vbfpair_lead_bjet_bTagWPM,nonResReg_vbfpair_lead_bjet_bTagWPT,nonResReg_vbfpair_lead_bjet_bTagWPXT,nonResReg_vbfpair_lead_bjet_bTagWPXXT,nonResReg_vbfpair_sublead_bjet_eta,nonResReg_vbfpair_sublead_bjet_phi,nonResReg_vbfpair_sublead_bjet_bTagWPL,nonResReg_vbfpair_sublead_bjet_bTagWPM,nonResReg_vbfpair_sublead_bjet_bTagWPT,nonResReg_vbfpair_sublead_bjet_bTagWPXT,nonResReg_vbfpair_sublead_bjet_bTagWPXXT,nonResReg_vbfpair_DeltaR_j1g1,nonResReg_vbfpair_DeltaR_j2g1,nonResReg_vbfpair_DeltaR_j1g2,nonResReg_vbfpair_DeltaR_j2g2,nonResReg_vbfpair_DeltaR_jg_min,nonResReg_vbfpair_CosThetaStar_CS,nonResReg_vbfpair_CosThetaStar_gg,nonResReg_vbfpair_CosThetaStar_jj,puppiMET_phi,puppiMET_pt,n_leptons,n_jets,nonResReg_vbfpair_chi_t0,nonResReg_vbfpair_chi_t1,nonResReg_vbfpair_DeltaPhi_j1MET,nonResReg_vbfpair_DeltaPhi_j2MET,nonResReg_vbfpair_VBF_first_jet_eta,nonResReg_vbfpair_VBF_first_jet_phi,nonResReg_vbfpair_VBF_second_jet_eta,nonResReg_vbfpair_VBF_second_jet_phi,nonResReg_vbfpair_VBF_first_jet_PtOverM,nonResReg_vbfpair_VBF_second_jet_PtOverM,nonResReg_vbfpair_VBF_jet_eta_prod,nonResReg_vbfpair_VBF_jet_eta_diff,nonResReg_vbfpair_VBF_jet_eta_sum,nonResReg_vbfpair_VBF_DeltaR_j1b1,nonResReg_vbfpair_VBF_DeltaR_j1b2,nonResReg_vbfpair_VBF_DeltaR_j2b1,nonResReg_vbfpair_VBF_DeltaR_j2b2,nonResReg_vbfpair_VBF_DeltaR_j1g1,nonResReg_vbfpair_VBF_DeltaR_j1g2,nonResReg_vbfpair_VBF_DeltaR_j2g1,nonResReg_vbfpair_VBF_DeltaR_j2g2,nonResReg_vbfpair_VBF_DeltaR_jb_min,nonResReg_vbfpair_VBF_DeltaR_jg_min,nonResReg_vbfpair_VBF_dijet_mass,nonResReg_vbfpair_HHbbggCandidate_eta,diphoton_PtOverM_ggjj,nonResReg_vbfpair_dijet_PtOverM_ggjj,nonResReg_vbfpair_lead_bjet_over_M_regressed,nonResReg_vbfpair_sublead_bjet_over_M_regressed,nonResReg_vbfpair_dijet_mass_DNNreg,AUX_event,AUX_lumi,AUX_hash,AUX_sample_name,AUX_sample_era,AUX_weight,AUX_eventWeight,AUX_mass,AUX_nonResReg_vbfpair_dijet_mass_DNNreg,AUX_nonResReg_vbfpair_HHbbggCandidate_mass,AUX_nonResReg_vbfpair_max_nonbjet_btag,AUX_nonResReg_vbfpair_resolved_BDT_mask,AUX_label1D,AUX_eventWeightTrain,AUX_DnonRes,AUX_DRes,AUX_DggFHH,AUX_DVBFHH
0,0.492834,0.973863,-0.399358,-0.138664,-0.069700,-1.074184,0.347193,-0.397451,1.033224,1.258086,1.892248,2.181186,2.360074,2.727974,-1.083040,-1.560878,-0.845981,-0.518928,-0.405253,-0.389385,-0.300604,0.462902,0.966620,0.271108,-0.867357,0.114560,0.936510,1.080180,0.844649,-1.430195,0.291790,-0.190083,-1.123356,-9.0,-9.0,-0.995910,-0.129666,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,0.201230,0.304589,0.698051,0.909282,-0.679736,-0.286862,7148.0,153.0,0.0,GluGluToHH_kl1p00_kt1p00_c20p00,Run3_2024/sim,0.000006,0.000060,127.370713,111.311968,425.238557,0.007258,1.0,2,0.000060,0.004668,0.025433,0.959048,0.010850
1,-1.298404,-1.967691,0.824803,0.089475,-1.234737,1.543527,0.381872,-0.431248,-0.769119,1.258086,1.892248,2.181186,2.360074,2.727974,-1.354262,-0.776012,1.191371,2.145759,2.681141,2.894378,3.525604,0.827595,0.604307,0.029283,-0.234466,1.003997,-0.822505,1.549345,-0.258225,-0.658106,-0.448924,-0.190083,-1.123356,-9.0,-9.0,-0.108616,-0.121072,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-2.060124,0.754053,0.914810,0.518014,1.191798,-0.291019,7154.0,153.0,1.0,GluGluToHH_kl1p00_kt1p00_c20p00,Run3_2024/sim,0.000002,0.000022,123.036786,111.180941,496.108216,0.989624,0.0,2,0.000022,0.000278,0.004629,0.993048,0.002046
2,0.831775,1.102667,0.352064,-0.701501,0.894138,1.211137,0.202129,0.877833,-1.005836,-0.806527,-0.595399,-0.503607,-0.500069,-0.397978,0.090204,1.594928,1.191371,-0.518928,-0.405253,-0.389385,-0.300604,-0.230081,0.145401,0.013654,-1.319413,-0.520740,0.842612,0.747834,0.617738,-1.310703,0.621827,-0.190083,-0.389303,-9.0,-9.0,0.292914,-0.592353,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,0.788170,1.844257,-0.266329,-0.572386,0.398282,-1.434050,7156.0,153.0,2.0,GluGluToHH_kl1p00_kt1p00_c20p00,Run3_2024/sim,0.000008,0.000076,123.981862,75.154049,247.478440,0.066025,1.0,2,0.000076,0.122224,0.686589,0.186825,0.004362
3,-0.353129,0.335077,0.419520,0.189101,-1.348481,1.215224,0.244977,-0.201059,-0.843621,1.258086,1.892248,2.181186,2.360074,-0.397978,-0.810282,-1.387099,1.191371,2.145759,2.681141,2.894378,3.525604,-0.337433,1.087956,0.677994,-0.713143,0.331286,0.330517,-0.273500,0.372236,-1.144607,-0.895924,-0.190083,2.546906,-9.0,-9.0,0.288350,-0.241379,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-0.458878,-0.251932,2.369601,0.820460,0.900014,0.584901,7162.0,153.0,3.0,GluGluToHH_kl1p00_kt1p00_c20p00,Run3_2024/sim,0.000004,0.000035,126.278114,138.788839,376.356250,0.998169,1.0,2,0.000035,0.001786,0.016526,0.973765,0.007923
4,0.154130,0.341272,1.046932,0.115148,-0.186979,1.053388,0.409384,-0.357806,-0.710689,1.258086,1.892248,2.181186,2.360074,-0.397978,-0.532726,-0.958508,1.191371,2.145759,2.681141,2.894378,3.525604,0.718346,0.574886,0.916248,0.392177,1.884655,0.521286,1.174859,0.688617,0.186701,0.994546,-0.190083,-0.389303,-9.0,-9.0,-0.865869,-1.138274,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-9.0,-0.638224,1.228270,1.660900,4.941865,4.731671,-0.131228,7158.0,153.0,4.0,GluGluToHH_kl1p00_kt1p00_c20p00,Run3_2024/sim,0.000010,0.000097,125.125739,116.217368,1100.597238,0.974731,1.0,2,0.000097,0.000409,0.008338,0.980072,0.011181

In [6]:
fcp_preproc_sig24.head()

,DeltaR_b1l1,DeltaR_b1l2,DeltaR_b2l1,DeltaR_b2l2,DeltaR_j10l1,DeltaR_j10l2,DeltaR_j10l3,DeltaR_j10l4,DeltaR_j1l1,DeltaR_j1l2,DeltaR_j1l3,DeltaR_j1l4,DeltaR_j2l1,DeltaR_j2l2,DeltaR_j2l3,DeltaR_j2l4,DeltaR_j3l1,DeltaR_j3l2,DeltaR_j3l3,DeltaR_j3l4,DeltaR_j4l1,DeltaR_j4l2,DeltaR_j4l3,DeltaR_j4l4,DeltaR_j5l1,DeltaR_j5l2,DeltaR_j5l3,DeltaR_j5l4,DeltaR_j6l1,DeltaR_j6l2,DeltaR_j6l3,DeltaR_j6l4,DeltaR_j7l1,DeltaR_j7l2,DeltaR_j7l3,DeltaR_j7l4,DeltaR_j8l1,DeltaR_j8l2,DeltaR_j8l3,DeltaR_j8l4,DeltaR_j9l1,DeltaR_j9l2,DeltaR_j9l3,DeltaR_j9l4,GenPTH,HTXS_Higgs_pt,HTXS_Higgs_y,HTXS_njets30,HTXS_stage_0,Njets2p5,Res_CosThetaStar_CS,Res_CosThetaStar_gg,Res_CosThetaStar_jj,Res_DNNpair_CosThetaStar_CS,Res_DNNpair_CosThetaStar_gg,Res_DNNpair_CosThetaStar_jj,Res_DNNpair_DeltaPhi_j1MET,Res_DNNpair_DeltaPhi_j2MET,Res_DNNpair_DeltaR_j1g1,Res_DNNpair_DeltaR_j1g2,Res_DNNpair_DeltaR_j2g1,Res_DNNpair_DeltaR_j2g2,Res_DNNpair_DeltaR_jg_min,Res_DNNpair_FirstJet_PtOverM,Res_DNNpair_HHbbggCandidate_eta,Res_DNNpair_HHbbggCandidate_mass,Res_DNNpair_HHbbggCandidate_phi,Res_DNNpair_HHbbggCandidate_pt,Res_DNNpair_Higgs_toGG_genMatched,Res_DNNpair_Higgs_tobb_genMatched,Res_DNNpair_MET_phiPNetCorr,Res_DNNpair_MET_ptPNetCorr,Res_DNNpair_M_X,Res_DNNpair_SecondJet_PtOverM,Res_DNNpair_chi_t0,Res_DNNpair_chi_t1,Res_DNNpair_dijet_DNNpair_Score,Res_DNNpair_dijet_charge,Res_DNNpair_dijet_eta,Res_DNNpair_dijet_mass,Res_DNNpair_dijet_mass_DNNreg,Res_DNNpair_dijet_phi,Res_DNNpair_dijet_pt,Res_DNNpair_has_atleast_one_fatjet,Res_DNNpair_has_two_btagged_jets,Res_DNNpair_lead_bjet_PNetRegPtRawCorr,Res_DNNpair_lead_bjet_PNetRegPtRawCorrNeutrino,Res_DNNpair_lead_bjet_PNetRegPtRawRes,Res_DNNpair_lead_bjet_UParTRegPtRawCorr,Res_DNNpair_lead_bjet_UParTRegPtRawCorrNeutrino,Res_DNNpair_lead_bjet_UParTRegPtRawRes,Res_DNNpair_lead_bjet_btagPNetB,Res_DNNpair_lead_bjet_btagPNetCvL,Res_DNNpair_lead_bjet_btagUParTAK4B,Res_DNNpair_lead_bjet_btagUParTAK4CvL,Res_DNNpair_lead_bjet_charge,Res_DNNpair_lead_bjet_eta,Res_DNNpair_lead_bjet_genFlav,Res_DNNpair_lead_bjet_genMatched,Res_DNNpair_lead_bjet_genMotherPdgId,Res_DNNpair_lead_bjet_genPdgId,Res_DNNpair_lead_bjet_hFlav,Res_DNNpair_lead_bjet_jet_idx,Res_DNNpair_lead_bjet_mass,Res_DNNpair_lead_bjet_phi,Res_DNNpair_lead_bjet_pt,Res_DNNpair_lead_bjet_pt_orig,Res_DNNpair_lead_bjet_rawFactor,Res_DNNpair_pholead_PtOverM,Res_DNNpair_phosublead_PtOverM,Res_DNNpair_sublead_bjet_PNetRegPtRawCorr,Res_DNNpair_sublead_bjet_PNetRegPtRawCorrNeutrino,Res_DNNpair_sublead_bjet_PNetRegPtRawRes,Res_DNNpair_sublead_bjet_UParTRegPtRawCorr,Res_DNNpair_sublead_bjet_UParTRegPtRawCorrNeutrino,Res_DNNpair_sublead_bjet_UParTRegPtRawRes,Res_DNNpair_sublead_bjet_btagPNetB,Res_DNNpair_sublead_bjet_btagPNetCvL,Res_DNNpair_sublead_bjet_btagUParTAK4B,Res_DNNpair_sublead_bjet_btagUParTAK4CvL,Res_DNNpair_sublead_bjet_charge,Res_DNNpair_sublead_bjet_eta,Res_DNNpair_sublead_bjet_genFlav,Res_DNNpair_sublead_bjet_genMatched,Res_DNNpair_sublead_bjet_genMotherPdgId,Res_DNNpair_sublead_bjet_genPdgId,Res_DNNpair_sublead_bjet_hFlav,Res_DNNpair_sublead_bjet_jet_idx,Res_DNNpair_sublead_bjet_mass,Res_DNNpair_sublead_bjet_phi,Res_DNNpair_sublead_bjet_pt,Res_DNNpair_sublead_bjet_pt_orig,Res_DNNpair_sublead_bjet_rawFactor,Res_DeltaPhi_j1MET,Res_DeltaPhi_j2MET,Res_DeltaR_j1g1,Res_DeltaR_j1g2,Res_DeltaR_j2g1,Res_DeltaR_j2g2,Res_DeltaR_jg_min,Res_FirstJet_PtOverM,Res_HHbbggCandidate_eta,Res_HHbbggCandidate_mass,Res_HHbbggCandidate_phi,Res_HHbbggCandidate_pt,Res_Higgs_toGG_genMatched,Res_Higgs_tobb_genMatched,Res_MET_phiPNetCorr,Res_MET_ptPNetCorr,Res_M_X,Res_SecondJet_PtOverM,Res_chi_t0,Res_chi_t1,Res_dijet_charge,Res_dijet_eta,Res_dijet_mass,Res_dijet_mass_DNNreg,Res_dijet_phi,Res_dijet_pt,Res_has_atleast_one_fatjet,Res_has_two_btagged_jets,Res_lead_bjet_PNetRegPtRawCorr,Res_lead_bjet_PNetRegPtRawCorrNeutrino,Res_lead_bjet_PNetRegPtRawRes,Res_lead_bjet_UParTRegPtRawCorr,Res_lead_bjet_UParTRegPtRawCorrNeutrino,Res_lead_bjet_UParTRegPtRawRes,Res_lead_bjet_btagPNetB,Res_lead_bjet_btagPNetCvL,Res_lead_bjet_btagUParTAK4B,Res_lead_bjet_btagUParTAK4CvL,Res_lead_bjet_charge,Res_lead_bjet_eta,Res_lead_bjet_genFlav,Res_lead_bjet_genMatched,Res_lead_bjet_genMotherPdgId,Res_lead_bjet_genPdgId,Res_lead_bjet_hFlav,Res_lead_bjet_jet_idx,Res_lead_bjet_mass,Res_lead_bjet_phi,Res_lead_bjet_pt,Res_lead_bjet_pt_orig,Res_lead_bjet_rawFactor,Res_pholead_PtOverM,Res_phosublead_PtOverM,Res_sublead_bjet_PNetRegPtRawCorr,Res_sublead_bjet_PNetRegPtRawCorrNeutrino,Res_sublead_bjet_PNetRegPtRawRes,Res_sublead_bjet_UParTRegPtRawCorr,Res_sublead_bjet_UParTRegPtRawCorrNeutrino,Res_sublead_bjet_UParTRegPtRawRes,Res_sublead_bjet_btagPNetB,Res_sublead_bjet_btagPNetCvL,Res_sublead_bjet_btagUParTAK4B,Res_sublead_bjet_btagUParTAK4CvL,Res_sublead_bjet_charge,Res_sublead_bjet_eta,Res_sublead_bjet_genFlav,Res_sublead_bjet_genMatched,Res_sublead_bjet_genMotherPdgId,Res_sublead_bjet_genPdgId,Res_sublead_bjet_hFlav,Res_sublead_bjet_jet_idx,Res_sublead_bjet_mass,Res_sublead_bjet_phi,Res_sublead_bjet_pt,Res_sublead_bjet_pt_orig,Res_sublead_bjet_rawFactor,charge,dZ,eta,event,fatjet1_area,fatjet1_chEmEF,fatjet1_chHEF,fatjet1_chMultiplicity,fatjet1_eta,fatjet1_event_id,fatjet1_genFlav,fatjet1_genMatched,fatjet1_genMatched_Hbb,fatjet1_genjetAK8_eta,fatjet1_genjetAK8_hadronFlavour,fatjet1_genjetAK8_mass,fatjet1_genjetAK8_nBHadrons,fatjet1_genjetAK8_nCHadrons,fatjet1_genjetAK8_partonFlavour,fatjet1_genjetAK8_phi,fatjet1_genjetAK8_pt,fatjet1_globalParT3_QCD,fatjet1_globalParT3_TopbWev,fatjet1_globalParT3_TopbWmv,fatjet1_globalParT3_TopbWq,fatjet1_globalParT3_TopbWqq,fatjet1_globalParT3_TopbWtauhv,fatjet1_globalParT3_WvsQCD,fatjet1_globalParT3_XWW3q,fatjet1_globalParT3_XWW4q,fatjet1_globalParT3_XWWqqev,fatjet1_globalParT3_XWWqqmv,fatjet1_globalParT3_Xbb,fatjet1_globalParT3_Xcc,fatjet1_globalParT3_Xcs,fatjet1_globalParT3_Xqq,fatjet1_globalParT3_Xtauhtaue,fatjet1_globalParT3_Xtauhtauh,fatjet1_globalParT3_Xtauhtaum,fatjet1_globalParT3_massCorrGeneric,fatjet1_globalParT3_massCorrX2p,fatjet1_globalParT3_withMassTopvsQCD,fatjet1_globalParT3_withMassWvsQCD,fatjet1_globalParT3_withMassZvsQCD,fatjet1_hadronFlavour,fatjet1_hfEmEF,fatjet1_hfHEF,fatjet1_mass,fatjet1_mass_jec,fatjet1_mass_jer,fatjet1_mass_nano,fatjet1_mass_raw,fatjet1_msoftdrop,fatjet1_muEF,fatjet1_n2b1,fatjet1_n3b1,fatjet1_nConstituents,fatjet1_neEmEF,fatjet1_neHEF,fatjet1_neMultiplicity,fatjet1_particleNetLegacy_QCD,fatjet1_particleNetLegacy_Xbb,fatjet1_particleNetLegacy_Xcc,fatjet1_particleNetLegacy_Xqq,fatjet1_particleNetLegacy_mass,fatjet1_particleNetWithMass_HbbvsQCD,fatjet1_particleNetWithMass_QCD,fatjet1_particleNet_QCD,fatjet1_particleNet_QCD0HF,fatjet1_particleNet_QCD1HF,fatjet1_particleNet_QCD2HF,fatjet1_particleNet_WVsQCD,fatjet1_particleNet_XbbVsQCD,fatjet1_particleNet_XccVsQCD,fatjet1_particleNet_XggVsQCD,fatjet1_particleNet_XqqVsQCD,fatjet1_particleNet_massCorr,fatjet1_phi,fatjet1_pt,fatjet1_pt_gen,fatjet1_pt_jec,fatjet1_pt_jer,fatjet1_pt_nano,fatjet1_pt_orig,fatjet1_pt_raw,fatjet1_rawFactor,fatjet1_rho_value,fatjet1_subjet1_UParTAK4RegPtRawCorr,fatjet1_subjet1_UParTAK4RegPtRawCorrNeutrino,fatjet1_subjet1_UParTAK4RegPtRawRes,fatjet1_subjet1_UParTAK4V1RegPtRawCorr,fatjet1_subjet1_UParTAK4V1RegPtRawCorrNeutrino,fatjet1_subjet1_UParTAK4V1RegPtRawRes,fatjet1_subjet1_area,fatjet1_subjet1_btagDeepFlavB,fatjet1_subjet1_btagUParTAK4B,fatjet1_subjet1_eta,fatjet1_subjet1_mass,fatjet1_subjet1_phi,fatjet1_subjet1_pt,fatjet1_subjet1_rawFactor,fatjet1_subjet1_subGenJetAK8Idx,fatjet1_subjet2_UParTAK4RegPtRawCorr,fatjet1_subjet2_UParTAK4RegPtRawCorrNeutrino,fatjet1_subjet2_UParTAK4RegPtRawRes,fatjet1_subjet2_UParTAK4V1RegPtRawCorr,fatjet1_subjet2_UParTAK4V1RegPtRawCorrNeutrino,fatjet1_subjet2_UParTAK4V1RegPtRawRes,fatjet1_subjet2_area,fatjet1_subjet2_btagDeepFlavB,fatjet1_subjet2_btagUParTAK4B,fatjet1_subjet2_eta,fatjet1_subjet2_mass,fatjet1_subjet2_phi,fatjet1_subjet2_pt,fatjet1_subjet2_rawFactor,fatjet1_subjet2_subGenJetAK8Idx,fatjet1_tau1,fatjet1_tau2,fatjet1_tau3,fatjet1_tau4,fatjet2_area,fatjet2_chEmEF,fatjet2_chHEF,fatjet2_chMultiplicity,fatjet2_eta,fatjet2_event_id,fatjet2_genFlav,fatjet2_genMatched,fatjet2_genMatched_Hbb,fatjet2_genjetAK8_eta,fatjet2_genjetAK8_hadronFlavour,fatjet2_genjetAK8_mass,fatjet2_genjetAK8_nBHadrons,fatjet2_genjetAK8_nCHadrons,fatjet2_genjetAK8_partonFlavour,fatjet2_genjetAK8_phi,fatjet2_genjetAK8_pt,fatjet2_globalParT3_QCD,fatjet2_globalParT3_TopbWev,fatjet2_globalParT3_TopbWmv,fatjet2_globalParT3_TopbWq,fatjet2_globalParT3_TopbWqq,fatjet2_globalParT3_TopbWtauhv,fatjet2_globalParT3_WvsQCD,fatjet2_globalParT3_XWW3q,fatjet2_globalParT3_XWW4q,fatjet2_globalParT3_XWWqqev,fatjet2_globalParT3_XWWqqmv,fatjet2_globalParT3_Xbb,fatjet2_globalParT3_Xcc,fatjet2_globalParT3_Xcs,fatjet2_globalParT3_Xqq,fatjet2_globalParT3_Xtauhtaue,fatjet2_globalParT3_Xtauhtauh,fatjet2_globalParT3_Xtauhtaum,fatjet2_globalParT3_massCorrGeneric,fatjet2_globalParT3_massCorrX2p,fatjet2_globalParT3_withMassTopvsQCD,fatjet2_globalParT3_withMassWvsQCD,fatjet2_globalParT3_withMassZvsQCD,fatjet2_hadronFlavour,fatjet2_hfEmEF,fatjet2_hfHEF,fatjet2_mass,fatjet2_mass_jec,fatjet2_mass_jer,fatjet2_mass_nano,fatjet2_mass_raw,fatjet2_msoftdrop,fatjet2_muEF,fatjet2_n2b1,fatjet2_n3b1,fatjet2_nConstituents,fatjet2_neEmEF,fatjet2_neHEF,fatjet2_neMultiplicity,fatjet2_particleNetLegacy_QCD,fatjet2_particleNetLegacy_Xbb,fatjet2_particleNetLegacy_Xcc,fatjet2_particleNetLegacy_Xqq,fatjet2_particleNetLegacy_mass,fatjet2_particleNetWithMass_HbbvsQCD,fatjet2_particleNetWithMass_QCD,fatjet2_particleNet_QCD,fatjet2_particleNet_QCD0HF,fatjet2_particleNet_QCD1HF,fatjet2_particleNet_QCD2HF,fatjet2_particleNet_WVsQCD,fatjet2_particleNet_XbbVsQCD,fatjet2_particleNet_XccVsQCD,fatjet2_particleNet_XggVsQCD,fatjet2_particleNet_XqqVsQCD,fatjet2_particleNet_massCorr,fatjet2_phi,fatjet2_pt,fatjet2_pt_gen,fatjet2_pt_jec,fatjet2_pt_jer,fatjet2_pt_nano,fatjet2_pt_orig,fatjet2_pt_raw,fatjet2_rawFactor,fatjet2_rho_value,fatjet2_subjet1_UParTAK4RegPtRawCorr,fatjet2_subjet1_UParTAK4RegPtRawCorrNeutrino,fatjet2_subjet1_UParTAK4RegPtRawRes,fatjet2_subjet1_UParTAK4V1RegPtRawCorr,fatjet2_subjet1_UParTAK4V1RegPtRawCorrNeutrino,fatjet2_subjet1_UParTAK4V1RegPtRawRes,fatjet2_subjet1_area,fatjet2_subjet1_btagDeepFlavB,fatjet2_subjet1_btagUParTAK4B,fatjet2_subjet1_eta,fatjet2_subjet1_mass,fatjet2_subjet1_phi,fatjet2_subjet1_pt,fatjet2_subjet1_rawFactor,fatjet2_subjet1_subGenJetAK8Idx,fatjet2_subjet2_UParTAK4RegPtRawCorr,fatjet2_subjet2_UParTAK4RegPtRawCorrNeutrino,fatjet2_subjet2_UParTAK4RegPtRawRes,fatjet2_subjet2_UParTAK4V1RegPtRawCorr,fatjet2_subjet2_UParTAK4V1RegPtRawCorrNeutrino,fatjet2_subjet2_UParTAK4V1RegPtRawRes,fatjet2_subjet2_area,fatjet2_subjet2_btagDeepFlavB,fatjet2_subjet2_btagUParTAK4B,fatjet2_subjet2_eta,fatjet2_subjet2_mass,fatjet2_subjet2_phi,fatjet2_subjet2_pt,fatjet2_subjet2_rawFactor,fatjet2_subjet2_subGenJetAK8Idx,fatjet2_tau1,fatjet2_tau2,fatjet2_tau3,fatjet2_tau4,fatjet3_area,fatjet3_chEmEF,fatjet3_chHEF,fatjet3_chMultiplicity,fatjet3_eta,fatjet3_event_id,fatjet3_genFlav,fatjet3_genMatched,fatjet3_genMatched_Hbb,fatjet3_genjetAK8_eta,fatjet3_genjetAK8_hadronFlavour,fatjet3_genjetAK8_mass,fatjet3_genjetAK8_nBHadrons,fatjet3_genjetAK8_nCHadrons,fatjet3_genjetAK8_partonFlavour,fatjet3_genjetAK8_phi,fatjet3_genjetAK8_pt,fatjet3_globalParT3_QCD,fatjet3_globalParT3_TopbWev,fatjet3_globalParT3_TopbWmv,fatjet3_globalParT3_TopbWq,fatjet3_globalParT3_TopbWqq,fatjet3_globalParT3_TopbWtauhv,fatjet3_globalParT3_WvsQCD,fatjet3_globalParT3_XWW3q,fatjet3_globalParT3_XWW4q,fatjet3_globalParT3_XWWqqev,fatjet3_globalParT3_XWWqqmv,fatjet3_globalParT3_Xbb,fatjet3_globalParT3_Xcc,fatjet3_globalParT3_Xcs,fatjet3_globalParT3_Xqq,fatjet3_globalParT3_Xtauhtaue,fatjet3_globalParT3_Xtauhtauh,fatjet3_globalParT3_Xtauhtaum,fatjet3_globalParT3_massCorrGeneric,fatjet3_globalParT3_massCorrX2p,fatjet3_globalParT3_withMassTopvsQCD,fatjet3_globalParT3_withMassWvsQCD,fatjet3_globalParT3_withMassZvsQCD,fatjet3_hadronFlavour,fatjet3_hfEmEF,fatjet3_hfHEF,fatjet3_mass,fatjet3_mass_jec,fatjet3_mass_jer,fatjet3_mass_nano,fatjet3_mass_raw,fatjet3_msoftdrop,fatjet3_muEF,fatjet3_n2b1,fatjet3_n3b1,fatjet3_nConstituents,fatjet3_neEmEF,fatjet3_neHEF,fatjet3_neMultiplicity,fatjet3_particleNetLegacy_QCD,fatjet3_particleNetLegacy_Xbb,fatjet3_particleNetLegacy_Xcc,fatjet3_particleNetLegacy_Xqq,fatjet3_particleNetLegacy_mass,fatjet3_particleNetWithMass_HbbvsQCD,fatjet3_particleNetWithMass_QCD,fatjet3_particleNet_QCD,fatjet3_particleNet_QCD0HF,fatjet3_particleNet_QCD1HF,fatjet3_particleNet_QCD2HF,fatjet3_particleNet_WVsQCD,fatjet3_particleNet_XbbVsQCD,fatjet3_particleNet_XccVsQCD,fatjet3_particleNet_XggVsQCD,fatjet3_particleNet_XqqVsQCD,fatjet3_particleNet_massCorr,fatjet3_phi,fatjet3_pt,fatjet3_pt_gen,fatjet3_pt_jec,fatjet3_pt_jer,fatjet3_pt_nano,fatjet3_pt_orig,fatjet3_pt_raw,fatjet3_rawFactor,fatjet3_rho_value,fatjet3_subjet1_UParTAK4RegPtRawCorr,fatjet3_subjet1_UParTAK4RegPtRawCorrNeutrino,fatjet3_subjet1_UParTAK4RegPtRawRes,fatjet3_subjet1_UParTAK4V1RegPtRawCorr,fatjet3_subjet1_UParTAK4V1RegPtRawCorrNeutrino,fatjet3_subjet1_UParTAK4V1RegPtRawRes,fatjet3_subjet1_area,fatjet3_subjet1_btagDeepFlavB,fatjet3_subjet1_btagUParTAK4B,fatjet3_subjet1_eta,fatjet3_subjet1_mass,fatjet3_subjet1_phi,fatjet3_subjet1_pt,fatjet3_subjet1_rawFactor,fatjet3_subjet1_subGenJetAK8Idx,fatjet3_subjet2_UParTAK4RegPtRawCorr,fatjet3_subjet2_UParTAK4RegPtRawCorrNeutrino,fatjet3_subjet2_UParTAK4RegPtRawRes,fatjet3_subjet2_UParTAK4V1RegPtRawCorr,fatjet3_subjet2_UParTAK4V1RegPtRawCorrNeutrino,fatjet3_subjet2_UParTAK4V1RegPtRawRes,fatjet3_subjet2_area,fatjet3_subjet2_btagDeepFlavB,fatjet3_subjet2_btagUParTAK4B,fatjet3_subjet2_eta,fatjet3_subjet2_mass,fatjet3_subjet2_phi,fatjet3_subjet2_pt,fatjet3_subjet2_rawFactor,fatjet3_subjet2_subGenJetAK8Idx,fatjet3_tau1,fatjet3_tau2,fatjet3_tau3,fatjet3_tau4,fatjet4_area,fatjet4_chEmEF,fatjet4_chHEF,fatjet4_chMultiplicity,fatjet4_eta,fatjet4_event_id,fatjet4_genFlav,fatjet4_genMatched,fatjet4_genMatched_Hbb,fatjet4_genjetAK8_eta,fatjet4_genjetAK8_hadronFlavour,fatjet4_genjetAK8_mass,fatjet4_genjetAK8_nBHadrons,fatjet4_genjetAK8_nCHadrons,fatjet4_genjetAK8_partonFlavour,fatjet4_genjetAK8_phi,fatjet4_genjetAK8_pt,fatjet4_globalParT3_QCD,fatjet4_globalParT3_TopbWev,fatjet4_globalParT3_TopbWmv,fatjet4_globalParT3_TopbWq,fatjet4_globalParT3_TopbWqq,fatjet4_globalParT3_TopbWtauhv,fatjet4_globalParT3_WvsQCD,fatjet4_globalParT3_XWW3q,fatjet4_globalParT3_XWW4q,fatjet4_globalParT3_XWWqqev,fatjet4_globalParT3_XWWqqmv,fatjet4_globalParT3_Xbb,fatjet4_globalParT3_Xcc,fatjet4_globalParT3_Xcs,fatjet4_globalParT3_Xqq,fatjet4_globalParT3_Xtauhtaue,fatjet4_globalParT3_Xtauhtauh,fatjet4_globalParT3_Xtauhtaum,fatjet4_globalParT3_massCorrGeneric,fatjet4_globalParT3_massCorrX2p,fatjet4_globalParT3_withMassTopvsQCD,fatjet4_globalParT3_withMassWvsQCD,fatjet4_globalParT3_withMassZvsQCD,fatjet4_hadronFlavour,fatjet4_hfEmEF,fatjet4_hfHEF,fatjet4_mass,fatjet4_mass_jec,fatjet4_mass_jer,fatjet4_mass_nano,fatjet4_mass_raw,fatjet4_msoftdrop,fatjet4_muEF,fatjet4_n2b1,fatjet4_n3b1,fatjet4_nConstituents,fatjet4_neEmEF,fatjet4_neHEF,fatjet4_neMultiplicity,fatjet4_particleNetLegacy_QCD,fatjet4_particleNetLegacy_Xbb,fatjet4_particleNetLegacy_Xcc,fatjet4_particleNetLegacy_Xqq,fatjet4_particleNetLegacy_mass,fatjet4_particleNetWithMass_HbbvsQCD,fatjet4_particleNetWithMass_QCD,fatjet4_particleNet_QCD,fatjet4_particleNet_QCD0HF,fatjet4_particleNet_QCD1HF,fatjet4_particleNet_QCD2HF,fatjet4_particleNet_WVsQCD,fatjet4_particleNet_XbbVsQCD,fatjet4_particleNet_XccVsQCD,fatjet4_particleNet_XggVsQCD,fatjet4_particleNet_XqqVsQCD,fatjet4_particleNet_massCorr,fatjet4_phi,fatjet4_pt,fatjet4_pt_gen,fatjet4_pt_jec,fatjet4_pt_jer,fatjet4_pt_nano,fatjet4_pt_orig,fatjet4_pt_raw,fatjet4_rawFactor,fatjet4_rho_value,fatjet4_subjet1_UParTAK4RegPtRawCorr,fatjet4_subjet1_UParTAK4RegPtRawCorrNeutrino,fatjet4_subjet1_UParTAK4RegPtRawRes,fatjet4_subjet1_UParTAK4V1RegPtRawCorr,fatjet4_subjet1_UParTAK4V1RegPtRawCorrNeutrino,fatjet4_subjet1_UParTAK4V1RegPtRawRes,fatjet4_subjet1_area,fatjet4_subjet1_btagDeepFlavB,fatjet4_subjet1_btagUParTAK4B,fatjet4_subjet1_eta,fatjet4_subjet1_mass,fatjet4_subjet1_phi,fatjet4_subjet1_pt,fatjet4_subjet1_rawFactor,fatjet4_subjet1_subGenJetAK8Idx,fatjet4_subjet2_UParTAK4RegPtRawCorr,fatjet4_subjet2_UParTAK4RegPtRawCorrNeutrino,fatjet4_subjet2_UParTAK4RegPtRawRes,fatjet4_subjet2_UParTAK4V1RegPtRawCorr,fatjet4_subjet2_UParTAK4V1RegPtRawCorrNeutrino,fatjet4_subjet2_UParTAK4V1RegPtRawRes,fatjet4_subjet2_area,fatjet4_subjet2_btagDeepFlavB,fatjet4_subjet2_btagUParTAK4B,fatjet4_subjet2_eta,fatjet4_subjet2_mass,fatjet4_subjet2_phi,fatjet4_subjet2_pt,fatjet4_subjet2_rawFactor,fatjet4_subjet2_subGenJetAK8Idx,fatjet4_tau1,fatjet4_tau2,fatjet4_tau3,fatjet4_tau4,fiducialClassicalFlag,fiducialGeometricFlag,fixedGridRhoAll,genHiggs_toGG_eta,genHiggs_toGG_eta_hardProc,genHiggs_toGG_mass,genHiggs_toGG_mass_hardProc,genHiggs_toGG_phi,genHiggs_toGG_phi_hardProc,genHiggs_toGG_pt,genHiggs_toGG_pt_hardProc,genHiggs_tobb_eta,genHiggs_tobb_eta_hardProc,genHiggs_tobb_mass,genHiggs_tobb_mass_hardProc,genHiggs_tobb_phi,genHiggs_tobb_phi_hardProc,genHiggs_tobb_pt,genHiggs_tobb_pt_hardProc,genWeight,gen_CosThetaStar_HH,gen_CosThetaStar_HH_hardProc,gen_mHH,gen_mHH_hardProc,gen_pT_HH,gen_pT_HH_hardProc,is_Res,is_Res_DNNpair,is_nonRes,is_nonResReg,is_nonResReg_DNNpair,is_nonResReg_vbfpair,jet10_PNetRegPtRawCorr,jet10_PNetRegPtRawCorrNeutrino,jet10_PNetRegPtRawRes,jet10_UParTRegPtRawCorr,jet10_UParTRegPtRawCorrNeutrino,jet10_UParTRegPtRawRes,jet10_btagDeepFlav_B,jet10_btagDeepFlav_CvB,jet10_btagDeepFlav_CvL,jet10_btagDeepFlav_QG,jet10_btagPNetB,jet10_btagPNetCvL,jet10_btagPNetQvG,jet10_btagUParTAK4B,jet10_btagUParTAK4CvL,jet10_btagUParTAK4QvG,jet10_chEmEF,jet10_chHEF,jet10_chMultiplicity,jet10_charge,jet10_eta,jet10_genFlav,jet10_genMatched,jet10_genMatched_Hbb,jet10_hFlav,jet10_index,jet10_jetId,jet10_mass,jet10_muEF,jet10_neEmEF,jet10_neHEF,jet10_neMultiplicity,jet10_phi,jet10_pt,jet10_pt_orig,jet10_rawFactor,jet1_PNetRegPtRawCorr,jet1_PNetRegPtRawCorrNeutrino,jet1_PNetRegPtRawRes,jet1_UParTRegPtRawCorr,jet1_UParTRegPtRawCorrNeutrino,jet1_UParTRegPtRawRes,jet1_btagDeepFlav_B,jet1_btagDeepFlav_CvB,jet1_btagDeepFlav_CvL,jet1_btagDeepFlav_QG,jet1_btagPNetB,jet1_btagPNetCvL,jet1_btagPNetQvG,jet1_btagUParTAK4B,jet1_btagUParTAK4CvL,jet1_btagUParTAK4QvG,jet1_chEmEF,jet1_chHEF,jet1_chMultiplicity,jet1_charge,jet1_eta,jet1_genFlav,jet1_genMatched,jet1_genMatched_Hbb,jet1_hFlav,jet1_index,jet1_jetId,jet1_mass,jet1_muEF,jet1_neEmEF,jet1_neHEF,jet1_neMultiplicity,jet1_phi,jet1_pt,jet1_pt_orig,jet1_rawFactor,jet2_PNetRegPtRawCorr,jet2_PNetRegPtRawCorrNeutrino,jet2_PNetRegPtRawRes,jet2_UParTRegPtRawCorr,jet2_UParTRegPtRawCorrNeutrino,jet2_UParTRegPtRawRes,jet2_btagDeepFlav_B,jet2_btagDeepFlav_CvB,jet2_btagDeepFlav_CvL,jet2_btagDeepFlav_QG,jet2_btagPNetB,jet2_btagPNetCvL,jet2_btagPNetQvG,jet2_btagUParTAK4B,jet2_btagUParTAK4CvL,jet2_btagUParTAK4QvG,jet2_chEmEF,jet2_chHEF,jet2_chMultiplicity,jet2_charge,jet2_eta,jet2_genFlav,jet2_genMatched,jet2_genMatched_Hbb,jet2_hFlav,jet2_index,jet2_jetId,jet2_mass,jet2_muEF,jet2_neEmEF,jet2_neHEF,jet2_neMultiplicity,jet2_phi,jet2_pt,jet2_pt_orig,jet2_rawFactor,jet3_PNetRegPtRawCorr,jet3_PNetRegPtRawCorrNeutrino,jet3_PNetRegPtRawRes,jet3_UParTRegPtRawCorr,jet3_UParTRegPtRawCorrNeutrino,jet3_UParTRegPtRawRes,jet3_btagDeepFlav_B,jet3_btagDeepFlav_CvB,jet3_btagDeepFlav_CvL,jet3_btagDeepFlav_QG,jet3_btagPNetB,jet3_btagPNetCvL,jet3_btagPNetQvG,jet3_btagUParTAK4B,jet3_btagUParTAK4CvL,jet3_btagUParTAK4QvG,jet3_chEmEF,jet3_chHEF,jet3_chMultiplicity,jet3_charge,jet3_eta,jet3_genFlav,jet3_genMatched,jet3_genMatched_Hbb,jet3_hFlav,jet3_index,jet3_jetId,jet3_mass,jet3_muEF,jet3_neEmEF,jet3_neHEF,jet3_neMultiplicity,jet3_phi,jet3_pt,jet3_pt_orig,jet3_rawFactor,jet4_PNetRegPtRawCorr,jet4_PNetRegPtRawCorrNeutrino,jet4_PNetRegPtRawRes,jet4_UParTRegPtRawCorr,jet4_UParTRegPtRawCorrNeutrino,jet4_UParTRegPtRawRes,jet4_btagDeepFlav_B,jet4_btagDeepFlav_CvB,jet4_btagDeepFlav_CvL,jet4_btagDeepFlav_QG,jet4_btagPNetB,jet4_btagPNetCvL,jet4_b

In [ ]:
print(f"preproc num mass window: {np.sum(fcp_preproc_sig24['mass'].gt(100).to_numpy(), fcp_preproc_sig24['mass'].lt(180).to_numpy())}")