In [2]:
import json
import os

import numpy as np
import prettytable as pt
import pandas as pd
import pyarrow.parquet as pq
from scipy.optimize import curve_fit
from scipy.integrate import quad

import hist
# import matplotlib.pyplot as plt
# from sklearn.metrics import roc_curve, roc_auc_score
# from scipy.integrate import trapezoid

import eos_utils as eos

# Workspace packages
from HHtobbyy.event_discrimination.DFDataset import DFDataset
from HHtobbyy.workspace_utils import match_sample
from HHtobbyy.event_discrimination.models import map_model_to_Model


dfdataset_config = "root://cmseos.fnal.gov//store/group/lpcdihiggsboost/tsievert/HiggsDNA_parquet/DFDatasets/vManosv6/24_Manosv6_2026-06-17_13-17-58/dataset_config.json"
dfdataset = DFDataset(dfdataset_config)
# model, model_config = "MLP", {"output_dirpath": "/uscms/home/tsievert/nobackup/XHYbbgg/Model_Outputs/ManosMLPv6/2026-06-17_13-17-58", "activation_func": "ELU"}
# model = map_model_to_Model(model)(dfdataset, model_config)

/store/group/lpcdihiggsboost/tsievert/HiggsDNA_parquet/DFDatasets/vManosv6/24_Manosv6_2026-06-17_13-17-58/dataset_config.json

In [51]:
cats = {
    "vbfhh_cat1": {
        "AUX_DVBFHH": 0.774,  # >
    },
    "cat1": {
        "AUX_DggFHH": 0.99292177413867067,  # >
        "AUX_DnonRes": 0.42667485697897478,  # <
        "AUX_DRes": 0.90612735576941672,  # <
    },
    "cat2": {
        "AUX_DggFHH": 0.68115907008322718,  # >
        "AUX_DnonRes": 0.00064209200655934,  # <
        "AUX_DRes": 0.96341029269140221,  # <
    },
    "cat3" : {
        "AUX_DggFHH": 0.87036774207656309,  # >
        "AUX_DnonRes": 0.00221775294750575,  # <
        "AUX_DRes": 0.84544492824676509,  # <
    }
}
filters = [[(col, '>' if col.endswith('HH') else '<', cut) for col, cut in cat.items()] for name, cat in cats.items()]
print(filters)
print('-'*60)

manos_cats = {
    "vbfhh_cat1": {
        "is_VBFHH_sig_score": 0.774,  # >
    },
    "cat1": {
        "is_ggHH_sig_score": 0.99292177413867067,  # >
        "is_nonRes_bkg_score": 0.42667485697897478,  # <
        "is_Res_bkg_score": 0.90612735576941672,  # <
    },
    "cat2": {
        "is_ggHH_sig_score": 0.68115907008322718,  # >
        "is_nonRes_bkg_score": 0.00064209200655934,  # <
        "is_Res_bkg_score": 0.96341029269140221,  # <
    },
    "cat3" : {
        "is_ggHH_sig_score": 0.87036774207656309,  # >
        "is_nonRes_bkg_score": 0.00221775294750575,  # <
        "is_Res_bkg_score": 0.84544492824676509,  # <
    }
}
manos_filters = [[(col, '>' if 'HH' in col else '<', cut) for col, cut in cat.items()] for name, cat in manos_cats.items()]
print(manos_filters)
print('-'*60)

[[('AUX_DVBFHH', '>', 0.774)], [('AUX_DggFHH', '>', 0.9929217741386707), ('AUX_DnonRes', '<', 0.4266748569789748), ('AUX_DRes', '<', 0.9061273557694167)], [('AUX_DggFHH', '>', 0.6811590700832272), ('AUX_DnonRes', '<', 0.00064209200655934), ('AUX_DRes', '<', 0.9634102926914022)], [('AUX_DggFHH', '>', 0.8703677420765631), ('AUX_DnonRes', '<', 0.00221775294750575), ('AUX_DRes', '<', 0.8454449282467651)]]
------------------------------------------------------------
[[('is_VBFHH_sig_score', '>', 0.774)], [('is_ggHH_sig_score', '>', 0.9929217741386707), ('is_nonRes_bkg_score', '<', 0.4266748569789748), ('is_Res_bkg_score', '<', 0.9061273557694167)], [('is_ggHH_sig_score', '>', 0.6811590700832272), ('is_nonRes_bkg_score', '<', 0.00064209200655934), ('is_Res_bkg_score', '<', 0.9634102926914022)], [('is_ggHH_sig_score', '>', 0.8703677420765631), ('is_nonRes_bkg_score', '<', 0.00221775294750575), ('is_Res_bkg_score', '<', 0.8454449282467651)]]
------------------------------------------------------------

In [23]:
filepaths = dfdataset.get_test_filepaths(0, regex='')
# filepaths = {'test': ['root://cmseos.fnal.gov//store/group/lpcdihiggsboost/tsievert/HiggsDNA_parquet/DFDatasets/vManosv6/24_Manosv6_2026-06-17_13-17-58/Run3_2024/sim/GluGlutoHH_kl-1p00_kt-1p00_c2-0p00/nominal/NOTAG_preprocessed_test0.parquet']}
test_pre = None
for filepath in filepaths['test']:
    try:
        eos_filepath = eos.load_file_eos(filepath)
        table = pq.read_table(eos_filepath, filters=filters)
        if test_pre is None: test_pre = table.to_pandas()
        else: test_pre = pd.concat([test_pre, table.to_pandas()])
        eos.delete_lockfile(eos_filepath)
    except:
        print('Failed loading: '+'/'.join(filepath.split('/')[-5:]))

dipho_mass_window = np.logical_and(test_pre['AUX_mass'].gt(100).to_numpy(), test_pre['AUX_mass'].lt(180).to_numpy())
pho_mva_cut = test_pre['AUX_pass_mva-0.7'].gt(0).to_numpy()
snt_cuts = np.logical_and(dipho_mass_window, pho_mva_cut)
test = test_pre.loc[snt_cuts]

Exception in thread Thread-317 (watch_tmp):
Traceback (most recent call last):
  File "/uscms/home/tsievert/nobackup/miniforge3/lib/python3.12/threading.py", line 1075, in _bootstrap_inner
    self.run()
  File "/uscms/home/tsievert/nobackup/miniforge3/lib/python3.12/threading.py", line 1012, in run
    self._target(*self._args, **self._kwargs)
  File "/uscms_data/d3/tsievert/XHYbbgg/eos-utils/src/eos_utils/watch_tmp.py", line 25, in watch_tmp
    raise TimeoutError(f"ERROR: Tmp file watching for {tmp_filepath} timed out.")
TimeoutError: ERROR: Tmp file watching for .tmp_load--5817468176195017662.parquet timed out.

Failed loading: 24_Manosv6_2026-06-17_13-17-58/Run3_2025/sim/ttHtoGG/NOTAG_preprocessed_test0.parquet

In [24]:
expected_eras = {
    # sim
    'Run2_2016postVFP/sim', 'Run2_2016preVFP/sim', 'Run2_2017/sim', 'Run2_2018/sim',
    'Run3_2022/sim/postEE', 'Run3_2022/sim/preEE', 'Run3_2023/sim/postBPix', 'Run3_2023/sim/preBPix', 'Run3_2024/sim', 'Run3_2025/sim',
    # data
    # 'Run2_2016postVFP/data', 'Run2_2016preVFP/data', 'Run2_2017/data', 'Run2_2018/data',
    # 'Run3_2022/data', 'Run3_2023/data', 'Run3_2024/data', 'Run3_2025/data'
}
set_of_unique_sample_eras = set(pd.unique(test_pre['AUX_sample_era']).tolist())
assert expected_eras == set_of_unique_sample_eras, f"sample eras do not match expected (either missing eras or names changed): \n {expected_eras} \n vs. \n {set_of_unique_sample_eras}"
for sample_era in pd.unique(test_pre['AUX_sample_era']):
    set_of_unique_sample_names = set(pd.unique(test_pre.loc[test_pre['AUX_sample_era'].eq(sample_era), 'AUX_sample_name']).tolist())
    if 'data' in sample_era:
        expected_set = {'Data'}
    elif 'sim' in sample_era:
        expected_set = {
            'DDQCDGJets', 'GGJets', 'TTGG', 
            'GluGluHToGG', 'VBFHToGG', 'VHToGG', 'ttHToGG', 'bbHToGG',
            'GluGluToHH_kl1p00_kt1p00_c20p00', 'VBFToHH_cv1p00_c2v1p00_c31p00'
        }
        if '201' in sample_era: expected_set.remove('bbHToGG')
        elif '2022' in sample_era: expected_set.remove('VBFToHH_cv1p00_c2v1p00_c31p00')
        elif 'Run3_2023/sim/postBPix' in sample_era: expected_set.remove('DDQCDGJets')
        elif '2025' in sample_era: expected_set.remove('ttHToGG')
    else:
        raise Exception(f"Improper naming for era, expected to either contain \'sim\' or \'data\': {sample_era}")
    assert set_of_unique_sample_names == expected_set, f"{sample_era} - samples names do not match expected: \n {expected_set} \n vs. \n {set_of_unique_sample_names}"
    # for sample_name in pd.unique(test_pre.loc[test_pre['AUX_sample_era'].eq(sample_era), 'AUX_sample_name']):
    #     print('-'*60, '\n', sample_name)


vbf23_mask = np.logical_and(
    test['AUX_sample_era'].isin(['Run3_2023/sim/preBPix', 'Run3_2023/sim/postBPix']),
    test['AUX_sample_name'].eq('VBFHH')
)  # makeup for lack of 2022 VBFHH signal 
test.loc[vbf23_mask, 'AUX_eventWeight'] = 1.78 * test.loc[vbf23_mask, 'AUX_eventWeight']
ddqcd23pre_mask = np.logical_and(
    test['AUX_sample_era'].isin(['Run3_2023/sim/preBPix']),
    test['AUX_sample_name'].eq('DDQCDGJets')
)  # makeup for lack of 2023postBPix DDQCDGJets 
test.loc[vbf23_mask, 'AUX_eventWeight'] = 1.53 * test.loc[ddqcd23pre_mask, 'AUX_eventWeight']
tth25_mask = np.logical_and(
    test['AUX_sample_era'].isin(['Run3_2024/sim']),
    test['AUX_sample_name'].eq('ttHToGG')
)  # makeup for lack of 2025 ttH 
test.loc[tth25_mask, 'AUX_eventWeight'] = 2 * test.loc[tth25_mask, 'AUX_eventWeight']

ValueError: Must have equal len keys and value when setting with an iterable

In [52]:
manos_sample = pd.read_parquet('/uscms/home/tsievert/nobackup/XHYbbgg/v6_merged_scored_events.parquet', filters=manos_filters)
manos_sample

,sample,year,lumi,event,run,mass,nonResReg_vbfpair_dijet_mass_DNNreg,is_boosted,y_proba,weight,weight_central,weight_interference,weight_nominal,rel_xsec_weight,weight_tot,score,is_nonRes_bkg_score,is_Res_bkg_score,is_ggHH_sig_score,is_VBFHH_sig_score
0,GGJets,2016,154,153393,1,139.009520,116.035283,False,-99.0,1.885662e-08,0.937809,0.0,0.093781,0.031976,0.031976,"[0.00025212744, 0.0023625302, 0.995826, 0.0015...",0.000252,0.002363,0.995826,0.001559
1,GGJets,2016,378,377019,1,116.795369,126.166095,False,-99.0,1.323452e-08,0.658201,0.0,0.065820,0.022442,0.022442,"[0.00033492837, 0.005860736, 0.9607204, 0.0330...",0.000335,0.005861,0.960720,0.033084
2,GGJets,2016,2996,2995889,1,171.404487,123.668745,False,-99.0,4.207334e-08,1.046231,0.0,0.209246,0.071345,0.071345,"[0.0013932141, 0.010970196, 0.98656505, 0.0010...",0.001393,0.010970,0.986565,0.001072
3,GGJets,2016,3638,3637360,1,117.708165,121.701889,False,-99.0,2.201736e-08,1.095004,0.0,0.109500,0.037335,0.037335,"[0.0012790998, 0.008000273, 0.9754558, 0.01526...",0.001279,0.008000,0.975456,0.015265
4,GGJets,2016,14186,14185188,1,157.113169,81.037684,False,-99.0,2.071010e-08,1.029989,0.0,0.102999,0.035119,0.035119,"[0.0021840138, 0.03671899, 0.95624703, 0.00484...",0.002184,0.036719,0.956247,0.004850
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
903923,Data,2025,1615,3460835794,398027,160.663539,103.918762,False,-99.0,1.000000e+00,1.000000,NaN,NaN,NaN,1.000000,"[0.0017438009, 0.017420232, 0.9764721, 0.00436...",0.001744,0.017420,0.976472,0.004364
903924,Data,2025,176,422329771,398391,122.647004,107.717850,False,-99.0,1.000000e+00,1.000000,NaN,NaN,NaN,1.000000,"[0.0021457057, 0.015055073, 0.97905135, 0.0037...",0.002146,0.015055,0.979051,0.003748
903925,Data,2025,214,481050706,398802,154.170830,87.753624,False,-99.0,1.000000e+00,1.000000,NaN,NaN,NaN,1.000000,"[0.0018607636, 0.020208234, 0.9748511, 0.00307...",0.001861,0.020208,0.974851,0.003080
903926,Data,2025,704,1746269700,398680,117.180525,81.437622,False,-99.0,1.000000e+00,1.000000,NaN,NaN,NaN,1.000000,"[0.0018443306, 0.06794319, 0.92502016, 0.00519...",0.001844,0.067943,0.925020,0.005192
903927,Data,2025,564,1287448231,398515,101.703616,154.594650,False,-99.0,1.000000e+00,1.000000,NaN,NaN,NaN,1.000000,"[0.0005909684, 0.007303509, 0.9887638, 0.00334...",0.000591,0.007304,0.988764,0.003342

In [33]:
test_sig = test.loc[test['AUX_sample_name'].eq('GluGluToHH_kl1p00_kt1p00_c20p00') & test['AUX_sample_era'].eq('Run3_2024/sim')]

In [38]:
def apply_cuts(df: pd.DataFrame, cuts: dict, init_mask: None|np.ndarray=None):
    if init_mask is None: init_mask = np.ones(len(df), dtype=bool)
    for cut_name, cut in cuts.items():
        init_mask = np.logical_and(
            init_mask, df.loc[:, cut_name].gt(cut).to_numpy() 
            if 'HH' in cut_name else (
                df.loc[:, cut_name].lt(cut).to_numpy() 
                if 'D' in cut_name or 'score' in cut_name else 
                df.loc[:, cut_name].eq(cut).to_numpy()
            )
        )
    return init_mask
cat1_test_sig = test_sig.loc[apply_cuts(test_sig, cats['cat1'])]
cat1_test_sig

,eta,lead_eta,lead_phi,lead_mvaID,sublead_eta,sublead_phi,sublead_mvaID,nonResReg_vbfpair_lead_bjet_eta,nonResReg_vbfpair_lead_bjet_phi,nonResReg_vbfpair_lead_bjet_bTagWPL,...,AUX_nonResReg_vbfpair_HHbbggCandidate_mass,AUX_nonResReg_vbfpair_max_nonbjet_btag,AUX_pass_mva-0.7,AUX_nonResReg_vbfpair_resolved_BDT_mask,AUX_label1D,AUX_eventWeightTrain,AUX_DnonRes,AUX_DRes,AUX_DggFHH,AUX_DVBFHH
0,-1.298404,-1.967691,0.824803,0.089475,-1.234737,1.543527,0.381872,-0.431248,-0.769119,1.258086,...,496.108216,0.989624,1,False,2,0.000022,0.000278,0.004629,0.993048,0.002046
11,0.205454,0.423937,1.370450,-0.212640,-0.359401,-1.391589,0.551762,0.643332,-0.082838,1.258086,...,396.585798,0.519043,1,True,2,0.000052,0.000316,0.002484,0.994894,0.002307
12,-0.184096,-0.624009,-1.274383,0.522149,0.140061,-1.058245,0.509540,-0.240209,0.685368,1.258086,...,503.844023,0.996460,1,True,2,0.000028,0.000085,0.003709,0.994748,0.001458
17,-0.383465,-0.149539,1.520080,0.364584,-1.064645,1.580036,0.029058,-0.484075,0.032005,1.258086,...,517.242590,0.953125,1,True,2,0.000056,0.000173,0.001935,0.996052,0.001840
19,-0.785713,-0.951999,-1.582093,0.477888,-1.232642,-0.614831,0.208640,-1.434468,0.384296,1.258086,...,393.455958,0.998657,1,True,2,-0.000016,0.000503,0.003300,0.994184,0.002013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
29506,0.584178,0.853710,-0.513285,0.497219,0.655863,-1.172811,0.546172,-0.150883,1.030228,1.258086,...,536.121252,0.998413,1,True,2,0.000037,0.000122,0.002374,0.995050,0.002453
29511,-0.641196,-1.249338,0.667814,0.480889,-0.480843,0.352371,-0.893389,-0.257454,-1.100086,1.258086,...,541.529007,0.983643,1,False,2,0.000034,0.000186,0.003658,0.993899,0.002258
29520,0.770802,1.501468,-0.955498,-1.003196,0.556782,-1.199784,0.373561,1.235630,0.655131,1.258086,...,537.863736,0.995483,1,True,2,0.000055,0.000111,0.001500,0.995317,0.003071
29521,0.068526,-0.335856,1.168217,0.489648,0.648217,1.497211,-1.430388,0.670886,-0.279682,1.258086,...,436.237742,0.998779,1,True,2,0.000043,0.000229,0.002556,0.995494,0.001721
29523,0.393438,0.106774,0.103890,0.321731,0.991334,-0.200671,0.294246,0.707260,1.264901,1.258086,...,470.923379,0.998657,1,True,2,0.000172,0.000076,0.002876,0.995140,0.001909

In [39]:
manos_sig = manos_sample.loc[manos_sample['sample'].eq('GluGluToHH_kl-1p00_kt-1p00_c2-0p00') & manos_sample['year'].eq(2024)
manos_cat1_sig = manos_sig.loc[apply_cuts(manos_sig, manos_cats['cat1'])]
manos_cat1_sig

,sample,year,lumi,event,run,mass,nonResReg_vbfpair_dijet_mass_DNNreg,is_boosted,y_proba,weight,weight_central,weight_interference,weight_nominal,rel_xsec_weight,weight_tot,score,is_nonRes_bkg_score,is_Res_bkg_score,is_ggHH_sig_score,is_VBFHH_sig_score
1,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,153,7154,1,123.036786,111.180941,False,-99.0,0.000002,0.325072,0.0,0.010758,0.000022,0.000022,"[0.00027772892, 0.0046289414, 0.9930479, 0.002...",0.000278,0.004629,0.993048,0.002046
19,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,178,8324,1,121.812230,122.636068,False,-99.0,0.000005,0.775575,0.0,0.025666,0.000052,0.000052,"[0.00031565057, 0.0024838592, 0.9948939, 0.002...",0.000316,0.002484,0.994894,0.002307
20,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,178,8326,1,122.340466,116.118666,False,-99.0,0.000003,0.425223,0.0,0.014072,0.000028,0.000028,"[8.487522e-05, 0.0037092764, 0.9947478, 0.0014...",0.000085,0.003709,0.994748,0.001458
27,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,187,8748,1,127.468867,118.929858,False,-99.0,0.000006,0.845682,0.0,0.027987,0.000057,0.000057,"[0.00017260779, 0.0019353109, 0.9960522, 0.001...",0.000173,0.001935,0.996052,0.001840
34,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,194,9086,1,121.601944,114.028840,False,-99.0,-0.000002,0.238456,0.0,-0.007891,-0.000016,-0.000016,"[0.0005030726, 0.003299693, 0.9941843, 0.00201...",0.000503,0.003300,0.994184,0.002013
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
65765,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,7234,339960,1,124.323642,139.791342,False,-99.0,0.000004,0.560419,0.0,0.018546,0.000038,0.000038,"[0.00012217755, 0.0023741205, 0.9950506, 0.002...",0.000122,0.002374,0.995051,0.002453
65778,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,7565,355548,1,124.986364,110.253622,False,-99.0,0.000003,0.506867,0.0,0.016774,0.000034,0.000034,"[0.00018606793, 0.0036576404, 0.9938985, 0.002...",0.000186,0.003658,0.993899,0.002258
65801,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,7757,364576,1,125.010301,126.040223,False,-99.0,0.000006,0.822891,0.0,0.027232,0.000055,0.000055,"[0.00011149996, 0.0015002702, 0.995317, 0.0030...",0.000111,0.001500,0.995317,0.003071
65804,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,7799,366514,1,125.548579,118.947060,False,-99.0,0.000004,0.650667,0.0,0.021533,0.000044,0.000044,"[0.0002288539, 0.002555732, 0.995494, 0.001721...",0.000229,0.002556,0.995494,0.001721
65811,GluGluToHH_kl-1p00_kt-1p00_c2-0p00,2024,7799,366544,1,125.571883,125.329099,False,-99.0,0.000018,2.584415,0.0,0.085527,0.000173,0.000173,"[7.576092e-05, 0.0028756987, 0.99513996, 0.001...",0.000076,0.002876,0.995140,0.001909

In [43]:

print('All event #s the same: ',
    np.all(
        manos_cat1_sig['event'].to_numpy().astype(np.int_) 
        == cat1_test_sig['AUX_event'].to_numpy().astype(np.int_)
    )
)

print('All output scores the same (to float32 precision): ',
    np.all(
        np.isclose(
            manos_cat1_sig.loc[:, 
                ['is_nonRes_bkg_score', 'is_Res_bkg_score', 'is_ggHH_sig_score', 'is_VBFHH_sig_score']
            ].to_numpy().astype(np.float32),
            cat1_test_sig.loc[:, 
                ['AUX_DnonRes', 'AUX_DRes', 'AUX_DggFHH', 'AUX_DVBFHH']
            ].to_numpy().astype(np.float32)
        )
    )
)

print('Yield of SnT 24 signal: ', manos_cat1_sig['weight_tot'].sum())
print('Yield of FCP 24 signal: ', cat1_test_sig['AUX_eventWeight'].sum())

All event #s the same:  True
All output scores the same (to float32 precision):  True
Yield of SnT 24 signal:  0.4190844020082845
Yield of FCP 24 signal:  0.4165224825536524

In [26]:
#############################################################
# ASCii histogram for rapid plotting
def ascii_hist(x, bins=10, weights=None):
    N,X = np.histogram(x, bins=bins, weights=weights)
    width = 50
    nmax = np.max(N.max())
    for (xi, n) in zip(X,N):
        bar = '#'*int(n*width/nmax)
        xi = '{0: <8.4g}'.format(xi).ljust(10)
        print('{0}| {1}'.format(xi,bar))
def ascii_hist(x, bins=10, weights=None, fit=None):
    N,X = np.histogram(x, bins=bins, weights=weights)
    width = 50
    nmax = np.max([N.max(), fit.max()])
    if fit is None:
        for (xi, n) in zip(X,N):
            bar = '#'*int(n*width/nmax)
            xi = '{0: <8.4g}'.format(xi).ljust(10)
            print('{0}| {1}'.format(xi,bar))
    else:
        for (xi, n, fiti) in zip(X,N,fit):
            bar = '#'*int(n*width/nmax)
            if fiti > n: bar = bar + ' '*(int(fiti*width/nmax) - int(n*width/nmax)) + '+'
            else: bar = ''.join([bar[j] if j != int(fiti*width/nmax) else '+' for j in range(len(bar))])
            xi = '{0: <8.4g}'.format(xi).ljust(10)
            print('{0}| {1}'.format(xi,bar))

#############################################################
# Sideband fit functions for nonRes bkg estimaton
def exp_func(x, a, b):
    return a * np.exp(b * x)
def sd_hist(mass: np.ndarray, weight: np.ndarray, fit_bins: list[float]):
    return hist.Hist(
        hist.axis.Regular(int((fit_bins[1]-fit_bins[0])//fit_bins[2]), fit_bins[0], fit_bins[1], name="var", growth=False, underflow=False, overflow=False), 
        storage='weight'
    ).fill(var=mass, weight=weight)
def exp_mass_fit(mass: np.ndarray, weight: np.ndarray, fit_bins: list[float], sigma: bool=False):
    _hist_ = sd_hist(mass, weight, fit_bins)
    params, _ = curve_fit(
        exp_func, _hist_.axes.centers[0]-_hist_.axes.centers[0][0], _hist_.values(), p0=(_hist_.values()[0], -0.1), 
        sigma=np.where(_hist_.values() != 0, np.sqrt(_hist_.variances()), 0.76) if sigma else None
    )
    print(_hist_)
    ascii_hist(mass, bins=np.arange(fit_bins[0], fit_bins[1], fit_bins[2]), weights=weight, fit=exp_func(_hist_.axes.centers[0]-_hist_.axes.centers[0][0], a=params[0], b=params[1]))
    return _hist_, params
def est_yield(mass: np.ndarray, weight: np.ndarray, fit_bins: list[float], sr_masscut: list[float], sigma: bool=False):
    _hist_, fit_params = exp_mass_fit(mass, weight, fit_bins, sigma=sigma)
    return quad(exp_func, sr_masscut[0]-_hist_.axes.centers[0][0], sr_masscut[1]-_hist_.axes.centers[0][0], args=tuple(fit_params))[0] / fit_bins[2]

In [46]:
data_samples = [sample_name for sample_name in sorted(pd.unique(test['AUX_sample_name']).tolist()) if match_sample(sample_name, ['Data']) is not None]
sideband_samples = [sample_name for sample_name in sorted(pd.unique(test['AUX_sample_name']).tolist()) if match_sample(sample_name, ['GJet', 'TTG']) is not None]
non_sideband_samples = [sample_name for sample_name in sorted(pd.unique(test['AUX_sample_name']).tolist()) if sample_name not in data_samples+sideband_samples]
print(f"All samples: {sorted(pd.unique(test['AUX_sample_name']).tolist())}")
print(f"Data samples: {data_samples}")
print(f"nonRes MC samples: {sideband_samples}")
print(f"Res/Signal MC samples: {non_sideband_samples}")


# field_names = ['Category'] + non_sideband_samples + ['nonRes SB fit', 'data SB fit', 's/b with nonRes fit', 's/b with data fit']
# field_names = ['Category'] + non_sideband_samples + ['nonRes SB fit', 'data SB fit']
# field_names = ['Category'] + non_sideband_samples + sideband_samples + sideband_samples + ['nonRes SB fit', 'N Data SB', 'data SB fit']

field_names = ['Category'] + non_sideband_samples + sideband_samples + ['single-H', 'non-Res', 'N Data SB']
table = pt.PrettyTable(field_names=field_names, float_format=".5")

not_prev_cut_mask = {}
for i, (name, cuts) in enumerate(cats.items()):
    # if 'VBF' in name: continue

    for eras in [['Run2_2016preVFP/sim', 'Run2_2016postVFP/sim', 'Run2_2016preVFP/data', 'Run2_2016postVFP/data'], ['Run2_2017/sim', 'Run2_2017/data'], ['Run2_2018/sim', 'Run2_2018/data'], ['Run3_2022/sim/preEE', 'Run3_2022/sim/postEE', 'Run3_2022/data'], ['Run3_2023/sim/preBPix', 'Run3_2023/sim/postBPix', 'Run3_2023/data'], ['Run3_2024/sim', 'Run3_2024/data'], ['Run3_2025/sim', 'Run3_2025/data'], ['tot']]:
        if 'tot' not in eras:
            era_mask = test['AUX_sample_era'].isin(eras); evtwt_factor = 1
            era_name = eras[-1].split('_')[-1].replace('/data', '').replace('postVFP', '')
        else:
            era_mask = np.ones(len(test), dtype=bool); evtwt_factor = 1
            era_name = 'tot'
        new_row = [name+' '+era_name]
        nonRes_sideband = pd.DataFrame({'mass': pd.Series(dtype='float'), 'weight_tot': pd.Series(dtype='float')})

        singleH_yield = 0.
        nonRes_yield = 0.

        for sample in non_sideband_samples+sideband_samples:

            sample_mask = np.logical_and(era_mask, test['AUX_sample_name'].eq(sample))
            if sample+era_name not in not_prev_cut_mask: not_prev_cut_mask[sample+era_name] = sample_mask

            pass_cut_mask = not_prev_cut_mask[sample+era_name]
            if 'boost' not in name:
                pass_cut_mask = np.logical_and(
                    pass_cut_mask, np.logical_and(test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].gt(80), test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].lt(190))
                )
            
            pass_cut_mask = apply_cuts(test, cuts, init_mask=pass_cut_mask)
            pass_cut_sr_mask = np.logical_and(
                pass_cut_mask,
                np.logical_and(test.loc[:, 'AUX_mass'].gt(122.5).to_numpy(), test.loc[:, 'AUX_mass'].lt(127.).to_numpy())
            )
            new_row.append((evtwt_factor * test.loc[pass_cut_sr_mask, 'AUX_eventWeight']).sum())

            if 'H' in sample and 'HH' not in sample: singleH_yield += new_row[-1]
            elif 'H' not in sample: nonRes_yield += new_row[-1]

            not_prev_cut_mask[sample+era_name] = np.logical_and(not_prev_cut_mask[sample+era_name], ~pass_cut_mask)

        new_row.append(singleH_yield); new_row.append(nonRes_yield)

        # for sb_sample_name, sb_sample_arr in zip(['nonRes', 'data'], [sideband_samples, data_samples]):
        #     sb_mask = np.zeros(len(test), dtype=bool)
        #     for sample in sb_sample_arr: sb_mask = np.logical_or(sb_mask, test['AUX_sample_name'].eq(sample))
        #     if sb_sample_name not in not_prev_cut_mask: not_prev_cut_mask[sb_sample_name] = sb_mask

        #     pass_cut_mask = not_prev_cut_mask[sb_sample_name]
        #     if i != 0:
        #         pass_cut_mask = np.logical_and(
        #             pass_cut_mask, np.logical_and(test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].gt(80), test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].lt(190))
        #         )
        #     for cut_name, cut in cuts.items():
        #         pass_cut_mask = np.logical_and(
        #             pass_cut_mask, test.loc[:, cut_name].gt(cut).to_numpy() 
        #             if 'HH' in cut_name else (
        #                 test.loc[:, cut_name].lt(cut).to_numpy() 
        #                 if 'D' in cut_name else 
        #                 test.loc[:, cut_name].eq(cut).to_numpy()
        #             )
        #         )
        #     pass_cut_sb_mask = np.logical_and(
        #         pass_cut_mask,
        #         np.logical_or(test.loc[:, 'AUX_mass'].lt(115.).to_numpy(), test.loc[:, 'AUX_mass'].gt(135.).to_numpy())
        #     )
        #     if sb_sample_name == 'data':
        #         sb_window_mask = np.logical_and(test.loc[:, 'AUX_mass'].gt(100.).to_numpy(), test.loc[:, 'AUX_mass'].lt(180.).to_numpy())
        #         new_row.append(np.sum(np.logical_and(pass_cut_sb_mask, sb_window_mask)))
        #     if np.sum(pass_cut_sb_mask) != 0:
        #         sb_est_yield = est_yield(test.loc[pass_cut_sb_mask, 'AUX_mass'], test.loc[pass_cut_sb_mask, 'AUX_eventWeight'], [100., 180., 5.], [115., 135.])
        #     else:
        #         sb_est_yield = 0
        #     new_row.append(sb_est_yield)

        for sb_sample_name, sb_sample_arr in zip(['data'], [data_samples]):
            sb_mask = np.logical_and(era_mask, test['AUX_sample_name'].isin(sb_sample_arr))
            if sb_sample_name+era_name not in not_prev_cut_mask: not_prev_cut_mask[sb_sample_name+era_name] = sb_mask

            pass_cut_mask = not_prev_cut_mask[sb_sample_name+era_name]
            if 'boost' not in name:
                pass_cut_mask = np.logical_and(
                    pass_cut_mask, np.logical_and(test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].gt(80), test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].lt(190))
                )
            pass_cut_mask = apply_cuts(test, cuts, init_mask=pass_cut_mask)
            pass_cut_sb_mask = np.logical_and(
                pass_cut_mask,
                np.logical_or(test.loc[:, 'AUX_mass'].lt(120.).to_numpy(), test.loc[:, 'AUX_mass'].gt(130.).to_numpy())
            )
            sb_window_mask = np.logical_and(test.loc[:, 'AUX_mass'].gt(100.).to_numpy(), test.loc[:, 'AUX_mass'].lt(180.).to_numpy())
            new_row.append(np.sum(np.logical_and(pass_cut_sb_mask, sb_window_mask)))

        # sum_singleH = new_row[1] + sum(new_row[4:11])
        # new_row.append(new_row[2] / (sum_singleH + new_row[11]))
        # new_row.append(new_row[2] / (sum_singleH + new_row[12]))

        table.add_row(new_row)

print(table)

All samples: ['DDQCDGJets', 'GGJets', 'GluGluHToGG', 'GluGluToHH_kl1p00_kt1p00_c20p00', 'TTGG', 'VBFHToGG', 'VBFToHH_cv1p00_c2v1p00_c31p00', 'VHToGG', 'bbHToGG', 'ttHToGG']
Data samples: []
nonRes MC samples: ['DDQCDGJets', 'GGJets', 'TTGG']
Res/Signal MC samples: ['GluGluHToGG', 'GluGluToHH_kl1p00_kt1p00_c20p00', 'VBFHToGG', 'VBFToHH_cv1p00_c2v1p00_c31p00', 'VHToGG', 'bbHToGG', 'ttHToGG']
+-----------------+-------------+---------------------------------+----------+-------------------------------+----------+---------+----------+------------+----------+---------+----------+----------+-----------+
|     Category    | GluGluHToGG | GluGluToHH_kl1p00_kt1p00_c20p00 | VBFHToGG | VBFToHH_cv1p00_c2v1p00_c31p00 |  VHToGG  | bbHToGG | ttHToGG  | DDQCDGJets |  GGJets  |   TTGG  | single-H | non-Res  | N Data SB |
+-----------------+-------------+---------------------------------+----------+-------------------------------+----------+---------+----------+------------+----------+---------+----------+----------+-----------+
| vbfhh_cat1 2016 |   0.00346   |             0.00013             | 0.00177  |            0.00179            | 0.00013  | 0.00000 | -0.00031 |  0.00000   | 0.03607  | 0.00000 | 0.00505  | 0.03607  |     0     |
| vbfhh_cat1 2017 |   0.00248   |             0.00013             | 0.00093  |            0.00166            | -0.00037 | 0.00000 | 0.00002  |  0.00000   | 0.03905  | 0.00076 | 0.00306  | 0.03982  |     0     |
| vbfhh_cat1 2018 |   0.00489   |             0.00029             | 0.00148  |            0.00274            | 0.00055  | 0.00000 | -0.00042 |  0.00000   | 0.00000  | 0.00000 | 0.00650  | 0.00000  |     0     |
| vbfhh_cat1 2022 |   0.00478   |             0.00022             | 0.00773  |            0.00000            | 0.00000  | 0.00023 | 0.00034  |  0.00000   | 0.01767  | 0.00059 | 0.01308  | 0.01827  |     0     |
| vbfhh_cat1 2023 |   -0.00032  |             0.00015             | 0.00346  |            0.00190            | 0.00000  | 0.00002 | 0.00014  |  0.00000   | 0.07745  | 0.00000 | 0.00331  | 0.07745  |     0     |
| vbfhh_cat1 2024 |   0.02951   |             0.00050             | 0.00154  |            0.00528            | 0.00036  | 0.00078 | 0.00000  |  0.00000   | 0.10248  | 0.00000 | 0.03218  | 0.10248  |     0     |
| vbfhh_cat1 2025 |   -0.00465  |             0.00071             | 0.00648  |            0.00552            | -0.00063 | 0.00032 | 0.00000  |  0.00000   | 0.09972  | 0.00000 | 0.00151  | 0.09972  |     0     |
|  vbfhh_cat1 tot |   0.04014   |             0.00213             | 0.02338  |            0.01889            | 0.00004  | 0.00135 | -0.00023 |  0.00000   | 0.37244  | 0.00136 | 0.06468  | 0.37380  |     0     |
|    cat1 2016    |   0.01935   |             0.12109             | 0.00215  |            0.00030            | 0.00173  | 0.00000 | 0.01248  |  0.00000   | 0.11372  | 0.00003 | 0.03571  | 0.11375  |     0     |
|    cat1 2017    |   0.02904   |             0.13983             | 0.00026  |            0.00039            | 0.00878  | 0.00000 | 0.01203  |  0.00000   | 0.00000  | 0.00156 | 0.05011  | 0.00156  |     0     |
|    cat1 2018    |   0.03866   |             0.20446             | 0.00269  |            0.00058            | 0.02023  | 0.00000 | 0.01627  |  0.00000   | 0.12402  | 0.00000 | 0.07785  | 0.12402  |     0     |
|    cat1 2022    |   0.01809   |             0.10127             | 0.00084  |            0.00000            | 0.00584  | 0.00057 | 0.00524  |  0.00000   | 0.22447  | 0.00000 | 0.03059  | 0.22447  |     0     |
|    cat1 2023    |   0.00817   |             0.07843             | 0.00100  |            0.00035            | 0.00390  | 0.00083 | 0.00655  |  0.00000   | 0.17322  | 0.00000 | 0.02044  | 0.17322  |     0     |
|    cat1 2024    |   0.06198   |             0.32066             | 0.00228  |            0.00079            | 0.02528  | 0.00269 | 0.02662  |  0.00000   | 0.46763  | 0.00160 | 0.11885  | 0.46923  |     0     |
|    cat1 2025    |   0.03270   |             0.36328             | 0.00813  |            0.00076            | 0.03589  | 0.00170 | 0.00000  |  0.00000   | 0.71230  | 0.00485 | 0.07841  | 0.71714  |     0     |
|     cat1 tot    |   0.20799   |             1.32901             | 0.01735  |            0.00318            | 0.10165  | 0.00579 | 0.07919  |  0.00000   | 1.81536  | 0.00803 | 0.41196  | 1.82340  |     0     |
|    cat2 2016    |   0.03051   |             0.13236             | 0.00378  |            0.00195            | 0.02371  | 0.00000 | 0.10300  |  0.00000   | 0.51073  | 0.00283 | 0.16100  | 0.51356  |     0     |
|    cat2 2017    |   0.04318   |             0.15647             | 0.00322  |            0.00228            | 0.02437  | 0.00000 | 0.13488  |  0.00000   | 0.27939  | 0.00556 | 0.20566  | 0.28495  |     0     |
|    cat2 2018    |   0.08126   |             0.23001             | 0.00833  |            0.00345            | 0.04196  | 0.00000 | 0.20123  |  0.00000   | 0.16965  | 0.00471 | 0.33278  | 0.17436  |     0     |
|    cat2 2022    |   0.02170   |             0.11549             | 0.00147  |            0.00000            | 0.01838  | 0.00283 | 0.10814  |  0.00000   | 0.22623  | 0.00334 | 0.15253  | 0.22957  |     0     |
|    cat2 2023    |   0.03002   |             0.09130             | 0.00337  |            0.00203            | 0.01592  | 0.00073 | 0.10351  |  0.00000   | 0.11908  | 0.00109 | 0.15355  | 0.12018  |     0     |
|    cat2 2024    |   0.16111   |             0.39371             | 0.01761  |            0.00544            | 0.11491  | 0.00786 | 0.28396  |  0.00000   | 0.83516  | 0.01539 | 0.58545  | 0.85055  |     0     |
|    cat2 2025    |   0.10492   |             0.42548             | 0.00782  |            0.00627            | 0.12354  | 0.00758 | 0.00000  |  0.00000   | 0.82234  | 0.01712 | 0.24386  | 0.83946  |     0     |
|     cat2 tot    |   0.47271   |             1.54479             | 0.04559  |            0.02142            | 0.36281  | 0.01899 | 0.93473  |  0.00000   | 2.96258  | 0.05005 | 1.83484  | 3.01262  |     0     |
|    cat3 2016    |   0.17425   |             0.14187             | 0.01308  |            0.00181            | 0.11249  | 0.00000 | 0.26399  |  0.00000   | 0.91356  | 0.01486 | 0.56381  | 0.92842  |     0     |
|    cat3 2017    |   0.16878   |             0.15595             | 0.01906  |            0.00213            | 0.12909  | 0.00000 | 0.30758  |  0.00000   | 1.83011  | 0.02110 | 0.62451  | 1.85121  |     0     |
|    cat3 2018    |   0.27160   |             0.22780             | 0.02359  |            0.00320            | 0.19658  | 0.00000 | 0.42031  |  2.14522   | 1.44091  | 0.03515 | 0.91207  | 3.62128  |     0     |
|    cat3 2022    |   0.16355   |             0.12129             | 0.00761  |            0.00000            | 0.10942  | 0.00860 | 0.22768  |  0.00000   | 0.63721  | 0.01418 | 0.51686  | 0.65139  |     0     |
|    cat3 2023    |   0.08797   |             0.09693             | 0.01183  |            0.00192            | 0.06901  | 0.00708 | 0.16555  |  0.00000   | 0.88076  | 0.00739 | 0.34144  | 0.88816  |     0     |
|    cat3 2024    |   0.51985   |             0.41455             | 0.03629  |            0.00461            | 0.39062  | 0.02177 | 0.74631  |  0.00000   | 3.65387  | 0.07335 | 1.71485  | 3.72723  |     0     |
|    cat3 2025    |   0.42676   |             0.40533             | 0.06629  |            0.00493            | 0.39814  | 0.02960 | 0.00000  |  0.00000   | 2.61384  | 0.00900 | 0.92079  | 2.62284  |     0     |
|     cat3 tot    |   1.81275   |             1.56371             | 0.17775  |            0.01860            | 1.40535  | 0.06705 | 2.13142  |  2.14522   | 11.97026 | 0.17504 | 5.59433  | 14.29053 |     0     |
+-----------------+-------------+---------------------------------+----------+-------------------------------+----------+---------+----------+------------+----------+---------+----------+----------+-----------+

In [53]:
data_samples = [sample_name for sample_name in sorted(pd.unique(manos_sample['sample']).tolist()) if match_sample(sample_name, ['Data']) is not None]
sideband_samples = [sample_name for sample_name in sorted(pd.unique(manos_sample['sample']).tolist()) if match_sample(sample_name, ['GJet', 'TTG']) is not None]
non_sideband_samples = [sample_name for sample_name in sorted(pd.unique(manos_sample['sample']).tolist()) if sample_name not in data_samples+sideband_samples]
print(f"All samples: {sorted(pd.unique(manos_sample['sample']).tolist())}")
print(f"Data samples: {data_samples}")
print(f"nonRes MC samples: {sideband_samples}")
print(f"Res/Signal MC samples: {non_sideband_samples}")


# field_names = ['Category'] + non_sideband_samples + ['nonRes SB fit', 'data SB fit', 's/b with nonRes fit', 's/b with data fit']
# field_names = ['Category'] + non_sideband_samples + ['nonRes SB fit', 'data SB fit']
# field_names = ['Category'] + non_sideband_samples + sideband_samples + sideband_samples + ['nonRes SB fit', 'N Data SB', 'data SB fit']

field_names = ['Category'] + non_sideband_samples + sideband_samples + ['single-H', 'non-Res', 'N Data SB']
table = pt.PrettyTable(field_names=field_names, float_format=".5")

not_prev_cut_mask = {}
for i, (name, cuts) in enumerate(manos_cats.items()):
    # if 'VBF' in name: continue

    for eras in [[2016], [2017], [2018], [2022], [2023], [2024], [2025], ['tot']]:
        if 'tot' not in eras:
            era_mask = manos_sample['year'].isin(eras); evtwt_factor = 1
            era_name = str(eras[0])
        else:
            era_mask = np.ones(len(manos_sample), dtype=bool); evtwt_factor = 1
            era_name = 'tot'
        new_row = [name+' '+era_name]
        nonRes_sideband = pd.DataFrame({'mass': pd.Series(dtype='float'), 'weight_tot': pd.Series(dtype='float')})

        singleH_yield = 0.
        nonRes_yield = 0.

        for sample in non_sideband_samples+sideband_samples:

            sample_mask = np.logical_and(era_mask, manos_sample['sample'].eq(sample))
            if sample+era_name not in not_prev_cut_mask: not_prev_cut_mask[sample+era_name] = sample_mask

            pass_cut_mask = not_prev_cut_mask[sample+era_name]
            if 'boost' not in name:
                pass_cut_mask = np.logical_and(
                    pass_cut_mask, np.logical_and(manos_sample.loc[:, 'nonResReg_vbfpair_dijet_mass_DNNreg'].gt(80), manos_sample.loc[:, 'nonResReg_vbfpair_dijet_mass_DNNreg'].lt(190))
                )
            pass_cut_mask = apply_cuts(manos_sample, cuts, init_mask=pass_cut_mask)
            pass_cut_sr_mask = np.logical_and(
                pass_cut_mask,
                np.logical_and(manos_sample.loc[:, 'mass'].gt(122.5).to_numpy(), manos_sample.loc[:, 'mass'].lt(127.).to_numpy())
            )
            new_row.append((evtwt_factor * manos_sample.loc[pass_cut_sr_mask, 'weight_tot']).sum())

            if 'H' in sample and 'HH' not in sample: singleH_yield += new_row[-1]
            elif 'H' not in sample: nonRes_yield += new_row[-1]

            not_prev_cut_mask[sample+era_name] = np.logical_and(not_prev_cut_mask[sample+era_name], ~pass_cut_mask)

        new_row.append(singleH_yield); new_row.append(nonRes_yield)

        # for sb_sample_name, sb_sample_arr in zip(['nonRes', 'data'], [sideband_samples, data_samples]):
        #     sb_mask = np.zeros(len(test), dtype=bool)
        #     for sample in sb_sample_arr: sb_mask = np.logical_or(sb_mask, test['AUX_sample_name'].eq(sample))
        #     if sb_sample_name not in not_prev_cut_mask: not_prev_cut_mask[sb_sample_name] = sb_mask

        #     pass_cut_mask = not_prev_cut_mask[sb_sample_name]
        #     if i != 0:
        #         pass_cut_mask = np.logical_and(
        #             pass_cut_mask, np.logical_and(test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].gt(80), test.loc[:, 'AUX_nonResReg_vbfpair_dijet_mass_DNNreg'].lt(190))
        #         )
        #     for cut_name, cut in cuts.items():
        #         pass_cut_mask = np.logical_and(
        #             pass_cut_mask, test.loc[:, cut_name].gt(cut).to_numpy() 
        #             if 'HH' in cut_name else (
        #                 test.loc[:, cut_name].lt(cut).to_numpy() 
        #                 if 'D' in cut_name else 
        #                 test.loc[:, cut_name].eq(cut).to_numpy()
        #             )
        #         )
        #     pass_cut_sb_mask = np.logical_and(
        #         pass_cut_mask,
        #         np.logical_or(test.loc[:, 'AUX_mass'].lt(115.).to_numpy(), test.loc[:, 'AUX_mass'].gt(135.).to_numpy())
        #     )
        #     if sb_sample_name == 'data':
        #         sb_window_mask = np.logical_and(test.loc[:, 'AUX_mass'].gt(100.).to_numpy(), test.loc[:, 'AUX_mass'].lt(180.).to_numpy())
        #         new_row.append(np.sum(np.logical_and(pass_cut_sb_mask, sb_window_mask)))
        #     if np.sum(pass_cut_sb_mask) != 0:
        #         sb_est_yield = est_yield(test.loc[pass_cut_sb_mask, 'AUX_mass'], test.loc[pass_cut_sb_mask, 'AUX_eventWeight'], [100., 180., 5.], [115., 135.])
        #     else:
        #         sb_est_yield = 0
        #     new_row.append(sb_est_yield)

        for sb_sample_name, sb_sample_arr in zip(['data'], [data_samples]):
            sb_mask = np.logical_and(era_mask, manos_sample['sample'].isin(sb_sample_arr))
            if sb_sample_name+era_name not in not_prev_cut_mask: not_prev_cut_mask[sb_sample_name+era_name] = sb_mask

            pass_cut_mask = not_prev_cut_mask[sb_sample_name+era_name]
            if 'boost' not in name:
                pass_cut_mask = np.logical_and(
                    pass_cut_mask, np.logical_and(manos_sample.loc[:, 'nonResReg_vbfpair_dijet_mass_DNNreg'].gt(80), manos_sample.loc[:, 'nonResReg_vbfpair_dijet_mass_DNNreg'].lt(190))
                )
            pass_cut_mask = apply_cuts(manos_sample, cuts, init_mask=pass_cut_mask)
            pass_cut_sb_mask = np.logical_and(
                pass_cut_mask,
                np.logical_or(manos_sample.loc[:, 'mass'].lt(120.).to_numpy(), manos_sample.loc[:, 'mass'].gt(130.).to_numpy())
            )
            sb_window_mask = np.logical_and(manos_sample.loc[:, 'mass'].gt(100.).to_numpy(), manos_sample.loc[:, 'mass'].lt(180.).to_numpy())
            new_row.append(np.sum(np.logical_and(pass_cut_sb_mask, sb_window_mask)))

        # sum_singleH = new_row[1] + sum(new_row[4:11])
        # new_row.append(new_row[2] / (sum_singleH + new_row[11]))
        # new_row.append(new_row[2] / (sum_singleH + new_row[12]))

        table.add_row(new_row)

print(table)

All samples: ['DDQCDGJets', 'Data', 'GGJets', 'GluGluHToGG', 'GluGluToHH_kl-1p00_kt-1p00_c2-0p00', 'TTGG', 'VBFHH_CV-1p000_C2V-1p000_C3-1p000', 'VBFHToGG', 'VHToGG', 'ttHToGG']
Data samples: ['Data']
nonRes MC samples: ['DDQCDGJets', 'GGJets', 'TTGG']
Res/Signal MC samples: ['GluGluHToGG', 'GluGluToHH_kl-1p00_kt-1p00_c2-0p00', 'VBFHH_CV-1p000_C2V-1p000_C3-1p000', 'VBFHToGG', 'VHToGG', 'ttHToGG']
+-----------------+-------------+------------------------------------+-----------------------------------+----------+----------+----------+------------+---------+---------+----------+----------+-----------+
|     Category    | GluGluHToGG | GluGluToHH_kl-1p00_kt-1p00_c2-0p00 | VBFHH_CV-1p000_C2V-1p000_C3-1p000 | VBFHToGG |  VHToGG  | ttHToGG  | DDQCDGJets |  GGJets |   TTGG  | single-H | non-Res  | N Data SB |
+-----------------+-------------+------------------------------------+-----------------------------------+----------+----------+----------+------------+---------+---------+----------+----------+-----------+
| vbfhh_cat1 2016 |   0.00220   |              0.00011               |              0.00175              | 0.00088  | 0.00025  | -0.00031 |  0.00000   | 0.03191 | 0.00000 | 0.00302  | 0.03191  |     0     |
| vbfhh_cat1 2017 |   0.00291   |              0.00013               |              0.00165              | 0.00062  | -0.00037 | 0.00002  |  0.00000   | 0.01445 | 0.00000 | 0.00319  | 0.01445  |     0     |
| vbfhh_cat1 2018 |   0.00428   |              0.00027               |              0.00275              | 0.00187  | 0.00055  | -0.00022 |  0.00000   | 0.00000 | 0.00000 | 0.00648  | 0.00000  |     1     |
| vbfhh_cat1 2022 |   0.00476   |              0.00022               |              0.00186              | 0.00771  | 0.00000  | 0.00034  |  0.00000   | 0.01285 | 0.00084 | 0.01281  | 0.01368  |     0     |
| vbfhh_cat1 2023 |   -0.00032  |              0.00015               |              0.00138              | 0.00347  | 0.00000  | 0.00014  |  0.00000   | 0.05267 | 0.00000 | 0.00329  | 0.05267  |     1     |
| vbfhh_cat1 2024 |   0.02965   |              0.00050               |              0.00552              | 0.00154  | 0.00035  | 0.00000  |  0.00000   | 0.06486 | 0.00000 | 0.03154  | 0.06486  |     7     |
| vbfhh_cat1 2025 |   -0.00464  |              0.00071               |              0.00574              | 0.00646  | -0.00063 | -0.00115 |  0.00000   | 0.09982 | 0.00000 | 0.00004  | 0.09982  |     2     |
|  vbfhh_cat1 tot |   0.03884   |              0.00209               |              0.02065              | 0.02255  | 0.00017  | -0.00118 |  0.00000   | 0.27656 | 0.00084 | 0.06038  | 0.27740  |     11    |
|    cat1 2016    |   0.01844   |              0.11560               |              0.00029              | 0.00196  | 0.00173  | 0.01121  |  0.00000   | 0.12869 | 0.00003 | 0.03334  | 0.12872  |     3     |
|    cat1 2017    |   0.02519   |              0.13399               |              0.00039              | 0.00026  | 0.00847  | 0.01097  |  0.00000   | 0.00000 | 0.00156 | 0.04489  | 0.00156  |     2     |
|    cat1 2018    |   0.03618   |              0.19848               |              0.00058              | 0.00269  | 0.01935  | 0.01553  |  0.00000   | 0.10205 | 0.00000 | 0.07375  | 0.10205  |     4     |
|    cat1 2022    |   0.01805   |              0.10115               |              0.00026              | 0.00084  | 0.00583  | 0.00523  |  0.00000   | 0.16233 | 0.00000 | 0.02995  | 0.16233  |     2     |
|    cat1 2023    |   0.00831   |              0.07941               |              0.00022              | 0.00102  | 0.00395  | 0.00663  |  0.00000   | 0.11774 | 0.00000 | 0.01991  | 0.11774  |     2     |
|    cat1 2024    |   0.06227   |              0.32263               |              0.00083              | 0.00229  | 0.02520  | 0.02677  |  0.00000   | 0.29599 | 0.00227 | 0.11654  | 0.29826  |     6     |
|    cat1 2025    |   0.03263   |              0.36298               |              0.00079              | 0.00811  | 0.03553  | 0.04440  |  0.00000   | 0.71301 | 0.00684 | 0.12067  | 0.71984  |     4     |
|     cat1 tot    |   0.20106   |              1.31422               |              0.00336              | 0.01716  | 0.10006  | 0.12076  |  0.00000   | 1.51980 | 0.01070 | 0.43904  | 1.53050  |     23    |
|    cat2 2016    |   0.02743   |              0.12731               |              0.00194              | 0.00347  | 0.02143  | 0.09294  |  0.00000   | 0.30255 | 0.00496 | 0.14526  | 0.30751  |     9     |
|    cat2 2017    |   0.04006   |              0.15056               |              0.00226              | 0.00189  | 0.02167  | 0.12203  |  0.00000   | 0.23279 | 0.00472 | 0.18564  | 0.23751  |     5     |
|    cat2 2018    |   0.07919   |              0.22378               |              0.00346              | 0.00754  | 0.04062  | 0.18723  |  0.00000   | 0.18773 | 0.00351 | 0.31459  | 0.19124  |     12    |
|    cat2 2022    |   0.02164   |              0.11534               |              0.00169              | 0.00147  | 0.01836  | 0.10795  |  0.00000   | 0.16350 | 0.00471 | 0.14942  | 0.16821  |     5     |
|    cat2 2023    |   0.03033   |              0.09244               |              0.00133              | 0.00339  | 0.01611  | 0.10487  |  0.00000   | 0.08086 | 0.00156 | 0.15471  | 0.08242  |     6     |
|    cat2 2024    |   0.16187   |              0.39613               |              0.00569              | 0.01769  | 0.11457  | 0.28557  |  0.00000   | 0.52862 | 0.02187 | 0.57970  | 0.55048  |     16    |
|    cat2 2025    |   0.10468   |              0.42513               |              0.00652              | 0.00780  | 0.12232  | 0.30769  |  0.00000   | 0.82315 | 0.02416 | 0.54249  | 0.84732  |     13    |
|     cat2 tot    |   0.46521   |              1.53068               |              0.02289              | 0.04324  | 0.35507  | 1.20829  |  0.00000   | 2.31920 | 0.06549 | 2.07181  | 2.38469  |     66    |
|    cat3 2016    |   0.15394   |              0.13863               |              0.00180              | 0.01078  | 0.10662  | 0.24016  |  0.00000   | 0.82826 | 0.01223 | 0.51150  | 0.84049  |     33    |
|    cat3 2017    |   0.15359   |              0.15263               |              0.00213              | 0.01765  | 0.12947  | 0.28799  |  0.00000   | 1.50319 | 0.01561 | 0.58870  | 1.51879  |     38    |
|    cat3 2018    |   0.24979   |              0.22499               |              0.00322              | 0.02422  | 0.19316  | 0.40066  |  1.86622   | 0.95036 | 0.03060 | 0.86783  | 2.84717  |     36    |
|    cat3 2022    |   0.16313   |              0.12113               |              0.00141              | 0.00759  | 0.10924  | 0.22728  |  0.00000   | 0.46152 | 0.02001 | 0.50724  | 0.48153  |     19    |
|    cat3 2023    |   0.08895   |              0.09815               |              0.00113              | 0.01196  | 0.06979  | 0.16733  |  0.00000   | 0.59638 | 0.01059 | 0.33803  | 0.60697  |     25    |
|    cat3 2024    |   0.52230   |              0.41710               |              0.00483              | 0.03645  | 0.38945  | 0.75055  |  0.00000   | 2.31273 | 0.10424 | 1.69874  | 2.41696  |     75    |
|    cat3 2025    |   0.42580   |              0.40500               |              0.00512              | 0.06611  | 0.39421  | 0.62069  |  0.00000   | 2.61643 | 0.01270 | 1.50681  | 2.62913  |     85    |
|     cat3 tot    |   1.75749   |              1.55763               |              0.01963              | 0.17476  | 1.39194  | 2.69467  |  1.86622   | 9.26886 | 0.20597 | 6.01885  | 11.34105 |    311    |
+-----------------+-------------+------------------------------------+-----------------------------------+----------+----------+----------+------------+---------+---------+----------+----------+-----------+

In [ ]:
manos_sample = pd.read_parquet('/uscms/home/tsievert/nobackup/XHYbbgg/v6_merged_scored_events.parquet')
manos_sample['lumievent'] = (manos_sample['lumi'].astype(int).astype(str) + manos_sample['event'].astype(int).astype(str)).astype(int)
manos_sample.keys()

In [ ]:
for sample in pd.unique(manos_sample['sample']):
    sample_mask = manos_sample['sample'].eq(sample)
    # for year in pd.unique(manos_sample['year']):
    #     year_mask = manos_sample['year'].eq(year)
    #     print(sample, ' ', year, ' ', len(manos_sample.loc[np.logical_and(sample_mask, year_mask)]))
    print('num events of ', sample, ' ', 'all years', ' ', len(manos_sample.loc[sample_mask]))
    print('-'*60)

In [ ]:
for sample in pd.unique(test['AUX_sample_name']):
    sample_mask = test['AUX_sample_name'].eq(sample)
    # for year, year_tags in zip(['2016', '2017', '2018', '2022', '2023', '2024', '2025'], [['Run2_2016preVFP/sim', 'Run2_2016postVFP/sim', 'Run2_2016preVFP/data', 'Run2_2016postVFP/data'], ['Run2_2017/sim', 'Run2_2017/data'], ['Run2_2018/sim', 'Run2_2018/data'], ['Run3_2022/sim/preEE', 'Run3_2022/sim/postEE', 'Run3_2022/data'], ['Run3_2023/sim/preBPix', 'Run3_2023/sim/postBPix', 'Run3_2023/data'], ['Run3_2024/sim', 'Run3_2024/data'], ['Run3_2025/sim', 'Run3_2025/data']]):
    #     year_mask = test['AUX_sample_era'].isin(year_tags)
    #     print(sample, ' ', year, ' ', len(test.loc[np.logical_and(sample_mask, year_mask)]))
    print('num events of ', sample, ' ', 'all years', ' ', len(test.loc[sample_mask]))
    print('-'*60)

In [ ]:
import awkward as ak
import numba as nb

@nb.njit
def issubset(subset_candidate_arr, superset_candidate_arr, nonsubset_builder):
    nonsubset_builder.begin_list()
    for sub_elem in subset_candidate_arr:
        found = False
        for super_elem in superset_candidate_arr:
            found = found or (sub_elem == super_elem)
        nonsubset_builder.append(sub_elem * found)
    nonsubset_builder.end_list()
    return nonsubset_builder

In [ ]:
nonsubset_events = issubset(test['lumievent'].to_numpy(), manos_sample['lumievent'].to_numpy(), ak.ArrayBuilder()).snapshot()
# nonsubset_events